name: easywear_models
version: 0.1.0
environment:
  sdk: ^3.6.1

dependencies:
  collection:
  crypto:
  uuid:
  meta:
  dart_jsonwebtoken: ^3.2.0
  auto_exporter_annotation: 1.0.3

dev_dependencies:
  auto_exporter: 3.5.1
  build_runner: ^2.4.6
  build_test: ^2.2.0
