import 'package:easywear_models/easywear_models.dart';

enum Category {
  accessories, // Zubehör
  miscellaneous, // Diverses
  shirt, // Hemd
  disposableClothing, // Einweg Bekleidung
  jacket, // Jacke
  overall, // Overall
  hearingProtection, // Gehörschutz
  shoes, // Schuhe
  other, // Sonstiges
  masks, // Masken
  gloves, // Handschuhe
  shorts, // Shorts
  vest, // Weste
  headProtection, // Kopfschutz
  eyeProtection, // Augenschutz
  sweatshirt, // Sweatshirt
  pkaClothing, // Bekleidung pka
  trousers, // Hose
  kneePads, // Kniepolster
  clothing, // Bekleidung
  tShirt, // Shirt
  bibPants, // Latzhose
  suspenders, // Hosenträger

  // hotfix
  einwegbekleidung,
  forstschutz,
  handschuhe,
  knieschutz,
  masken,
  pvcStiefel,
  regenkleidung,
  warnschutzkleidung,

  // hotfix diakonie workwear
  shirts,
  schlupfkasacks,
  poloshirts,
  hoodyjacken,
  sweatjacken,
}

extension CategoryExt on Category {
  String get string =>
      toString()
          .split(".")
          .last;

  static Category fromString(String s) => Category.values.firstWhere((country) => country.string == s);

  String uiText(Language language) {
    return switch (this) {
      Category.accessories =>
      switch (language) {
        Language.de => "Zubehör",
        Language.en => "Accessories",
        Language.fr => "Accessoires",
        Language.it => "Accessori",
        Language.es => "Accesorios",
        Language.nl => "Accessoires",
        Language.ru => "Аксессуары",
        Language.tr => "Aksesuarlar",
        Language.no => "Tilbehør",
        Language.da => "Tilbehør",
        Language.sv => "Accessoarer",
        Language.ar => "إكسسوارات",
        Language.zh => "饰品",
        Language.th => "เครื่องประดับ",
        Language.vi => "Phụ kiện",
        Language.cs => "Doplňky",
        Language.el => "Αξεσουάρ",
        Language.uk => "Аксесуари",
        Language.hr => "Pribor",
        Language.ja => "アクセサリー",
        Language.pl => "Akcesoria",
        Language.pt => "Acessórios",
        Language.ko => "액세서리",
        Language.ur => "لوازمات",
        Language.bg => "Аксесоари",
        Language.af => "Toebehore",
        Language.hi => "सहायक उपकरण",
      },
      Category.miscellaneous =>
      switch (language) {
        Language.de => "Sonstiges",
        Language.en => "Miscellaneous",
        Language.fr => "Divers",
        Language.it => "Varie",
        Language.es => "Miscelánea",
        Language.nl => "Diversen",
        Language.ru => "Разное",
        Language.tr => "Çeşitli",
        Language.no => "Diverse",
        Language.da => "Diverse",
        Language.sv => "Diverse",
        Language.ar => "متنوعات",
        Language.zh => "杂项",
        Language.th => "เบ็ดเตล็ด",
        Language.vi => "Linh tinh",
        Language.cs => "Různé",
        Language.el => "Διάφορα",
        Language.uk => "Різне",
        Language.hr => "Razno",
        Language.ja => "その他",
        Language.pl => "Różne",
        Language.pt => "Diversos",
        Language.ko => "기타",
        Language.ur => "متفرق",
        Language.bg => "Разни",
        Language.af => "Diverse",
        Language.hi => "विविध",
      },
      Category.shirt =>
      switch (language) {
        Language.de => "Hemd",
        Language.en => "Shirt",
        Language.fr => "Chemise",
        Language.it => "Camicia",
        Language.es => "Camisa",
        Language.nl => "Overhemd",
        Language.ru => "Рубашка",
        Language.tr => "Gömlek",
        Language.no => "Skjorte",
        Language.da => "Skjorte",
        Language.sv => "Skjorta",
        Language.ar => "قميص",
        Language.zh => "衬衫",
        Language.th => "เสื้อเชิ้ต",
        Language.vi => "Áo sơ mi",
        Language.cs => "Košile",
        Language.el => "Πουκάμισο",
        Language.uk => "Сорочка",
        Language.hr => "Košulja",
        Language.ja => "シャツ",
        Language.pl => "Koszula",
        Language.pt => "Camisa",
        Language.ko => "셔츠",
        Language.ur => "قمیض",
        Language.bg => "Риза",
        Language.af => "Hemp",
        Language.hi => "शर्ट",
      },
      Category.disposableClothing =>
      switch (language) {
        Language.de => "Einwegkleidung",
        Language.en => "Disposable Clothing",
        Language.fr => "Vêtements jetables",
        Language.it => "Abbigliamento monouso",
        Language.es => "Ropa desechable",
        Language.nl => "Wegwerpkleding",
        Language.ru => "Одноразовая одежда",
        Language.tr => "Tek kullanımlık giysi",
        Language.no => "Engangsklær",
        Language.da => "Engangsbeklædning",
        Language.sv => "Engångskläder",
        Language.ar => "ملابس يمكن التخلص منها",
        Language.zh => "一次性服装",
        Language.th => "เสื้อผ้าใช้แล้วทิ้ง",
        Language.vi => "Quần áo dùng một lần",
        Language.cs => "Jednorázové oděvy",
        Language.el => "Ρούχα μιας χρήσης",
        Language.uk => "Одноразовий одяг",
        Language.hr => "Jednokratna odjeća",
        Language.ja => "使い捨て衣類",
        Language.pl => "Odzież jednorazowa",
        Language.pt => "Roupa descartável",
        Language.ko => "일회용 의류",
        Language.ur => "ڈسپوزایبل لباس",
        Language.bg => "Облекло за еднократна употреба",
        Language.af => "Weggooibare klere",
        Language.hi => "डिस्पोजेबल कपड़े",
      },
      Category.jacket =>
      switch (language) {
        Language.de => "Jacke",
        Language.en => "Jacket",
        Language.fr => "Veste",
        Language.it => "Giacca",
        Language.es => "Chaqueta",
        Language.nl => "Jas",
        Language.ru => "Куртка",
        Language.tr => "Ceket",
        Language.no => "Jakke",
        Language.da => "Jakke",
        Language.sv => "Jacka",
        Language.ar => "سترة",
        Language.zh => "夹克",
        Language.th => "เสื้อแจ็คเก็ต",
        Language.vi => "Áo khoác",
        Language.cs => "Bunda",
        Language.el => "Μπουφάν",
        Language.uk => "Куртка",
        Language.hr => "Jakna",
        Language.ja => "ジャケット",
        Language.pl => "Kurtka",
        Language.pt => "Jaqueta",
        Language.ko => "재킷",
        Language.ur => "جیکٹ",
        Language.bg => "Яке",
        Language.af => "Baadjie",
        Language.hi => "जैकेट",
      },
      Category.overall =>
      switch (language) {
        Language.de => "Overall",
        Language.en => "Overall",
        Language.fr => "Combinaison",
        Language.it => "Tuta",
        Language.es => "Mono", // or "Overol" depending on region
        Language.nl => "Overall",
        Language.ru => "Комбинезон",
        Language.tr => "Tulum",
        Language.no => "Kjeledress",
        Language.da => "Overall", // or "Kjeldress"
        Language.sv => "Overall",
        Language.ar => "أفرول",
        Language.zh => "工装裤", // More specific: 连身裤 (liánshēnkù) for coveralls
        Language.th => "ชุดเอี๊ยม",
        Language.vi => "Quần yếm",
        Language.cs => "Kombinéza",
        Language.el => "Ολόσωμη φόρμα",
        Language.uk => "Комбінезон",
        Language.hr => "Kombinezon",
        Language.ja => "オーバーオール",
        Language.pl => "Kombinezon",
        Language.pt => "Macacão",
        Language.ko => "오버롤",
        Language.ur => "اوورآل",
        Language.bg => "Гащеризон",
        Language.af => "Oorpak",
        Language.hi => "ओवरऑल",
      },
      Category.hearingProtection =>
      switch (language) {
        Language.de => "Gehörschutz",
        Language.en => "Hearing Protection",
        Language.fr => "Protection auditive",
        Language.it => "Protezione dell'udito",
        Language.es => "Protección auditiva",
        Language.nl => "Gehoorbescherming",
        Language.ru => "Средства защиты слуха",
        Language.tr => "Kulak koruyucu",
        Language.no => "Hørselsvern",
        Language.da => "Høreværn",
        Language.sv => "Hörselskydd",
        Language.ar => "حماية السمع",
        Language.zh => "听力保护",
        Language.th => "อุปกรณ์ป้องกันการได้ยิน",
        Language.vi => "Bảo vệ thính giác",
        Language.cs => "Ochrana sluchu",
        Language.el => "Προστασία ακοής",
        Language.uk => "Засоби захисту слуху",
        Language.hr => "Zaštita sluha",
        Language.ja => "聴覚保護具",
        Language.pl => "Ochrona słuchu",
        Language.pt => "Proteção auditiva",
        Language.ko => "청력 보호",
        Language.ur => "سماعت کا تحفظ",
        Language.bg => "Защита на слуха",
        Language.af => "Gehoorbeskerming",
        Language.hi => "श्रवण सुरक्षा",
      },
      Category.shoes =>
      switch (language) {
        Language.de => "Schuhe",
        Language.en => "Shoes",
        Language.fr => "Chaussures",
        Language.it => "Scarpe",
        Language.es => "Zapatos",
        Language.nl => "Schoenen",
        Language.ru => "Обувь",
        Language.tr => "Ayakkabı",
        Language.no => "Sko",
        Language.da => "Sko",
        Language.sv => "Skor",
        Language.ar => "أحذية",
        Language.zh => "鞋子",
        Language.th => "รองเท้า",
        Language.vi => "Giày",
        Language.cs => "Boty",
        Language.el => "Παπούτσια",
        Language.uk => "Взуття",
        Language.hr => "Cipele",
        Language.ja => "靴",
        Language.pl => "Buty",
        Language.pt => "Sapatos",
        Language.ko => "신발",
        Language.ur => "جوتے",
        Language.bg => "Обувки",
        Language.af => "Skoene",
        Language.hi => "जूते",
      },
      Category.other =>
      switch (language) {
        Language.de => "Andere",
        Language.en => "Other",
        Language.fr => "Autre",
        Language.it => "Altro",
        Language.es => "Otro",
        Language.nl => "Overig",
        Language.ru => "Другое",
        Language.tr => "Diğer",
        Language.no => "Annet",
        Language.da => "Andet",
        Language.sv => "Övrigt",
        Language.ar => "آخر",
        Language.zh => "其他",
        Language.th => "อื่น ๆ",
        Language.vi => "Khác",
        Language.cs => "Ostatní",
        Language.el => "Άλλο",
        Language.uk => "Інше",
        Language.hr => "Ostalo",
        Language.ja => "その他",
        Language.pl => "Inne",
        Language.pt => "Outro",
        Language.ko => "기타",
        Language.ur => "دیگر",
        Language.bg => "Други",
        Language.af => "Ander",
        Language.hi => "अन्य",
      },
      Category.masks =>
      switch (language) {
        Language.de => "Masken",
        Language.en => "Masks",
        Language.fr => "Masques",
        Language.it => "Maschere",
        Language.es => "Mascarillas",
        Language.nl => "Maskers",
        Language.ru => "Маски",
        Language.tr => "Maskeler",
        Language.no => "Masker",
        Language.da => "Masker",
        Language.sv => "Masker",
        Language.ar => "أقنعة",
        Language.zh => "口罩",
        Language.th => "หน้ากาก",
        Language.vi => "Khẩu trang",
        Language.cs => "Masky",
        Language.el => "Μάσκες",
        Language.uk => "Маски",
        Language.hr => "Maske",
        Language.ja => "マスク",
        Language.pl => "Maski",
        Language.pt => "Máscaras",
        Language.ko => "마스크",
        Language.ur => "ماسک",
        Language.bg => "Маски",
        Language.af => "Maskers",
        Language.hi => "मास्क",
      },
      Category.gloves =>
      switch (language) {
        Language.de => "Handschuhe",
        Language.en => "Gloves",
        Language.fr => "Gants",
        Language.it => "Guanti",
        Language.es => "Guantes",
        Language.nl => "Handschoenen",
        Language.ru => "Перчатки",
        Language.tr => "Eldivenler",
        Language.no => "Hansker",
        Language.da => "Handsker",
        Language.sv => "Handskar",
        Language.ar => "قفازات",
        Language.zh => "手套",
        Language.th => "ถุงมือ",
        Language.vi => "Găng tay",
        Language.cs => "Rukavice",
        Language.el => "Γάντια",
        Language.uk => "Рукавички",
        Language.hr => "Rukavice",
        Language.ja => "手袋",
        Language.pl => "Rękawice",
        Language.pt => "Luvas",
        Language.ko => "장갑",
        Language.ur => "دستانے",
        Language.bg => "Ръкавици",
        Language.af => "Handskoene",
        Language.hi => "दस्ताने",
      },
      Category.shorts =>
      switch (language) {
        Language.de => "Kurze Hosen",
        Language.en => "Shorts",
        Language.fr => "Shorts",
        Language.it => "Pantaloncini",
        Language.es => "Pantalones cortos",
        Language.nl => "Korte broeken",
        Language.ru => "Шорты",
        Language.tr => "Şort",
        Language.no => "Shorts",
        Language.da => "Shorts",
        Language.sv => "Shorts",
        Language.ar => "شورت",
        Language.zh => "短裤",
        Language.th => "กางเกงขาสั้น",
        Language.vi => "Quần short",
        Language.cs => "Kraťasy",
        Language.el => "Σορτς",
        Language.uk => "Шорти",
        Language.hr => "Kratke hlače",
        Language.ja => "ショートパンツ",
        Language.pl => "Szorty",
        Language.pt => "Shorts", // or "Calções"
        Language.ko => "반바지",
        Language.ur => "شارٹس",
        Language.bg => "Къси панталони",
        Language.af => "Kortbroek",
        Language.hi => "शॉर्ट्स",
      },
      Category.vest =>
      switch (language) {
        Language.de => "Weste",
        Language.en => "Vest",
        Language.fr => "Gilet",
        Language.it => "Gilet", // or "Panciotto"
        Language.es => "Chaleco",
        Language.nl => "Vest", // Can also mean cardigan, "Gilet" is more specific for waistcoat type
        Language.ru => "Жилет",
        Language.tr => "Yelek",
        Language.no => "Vest",
        Language.da => "Vest",
        Language.sv => "Väst",
        Language.ar => "سترة", // Can also mean jacket, صدرية (sadria) is more specific
        Language.zh => "背心",
        Language.th => "เสื้อกั๊ก",
        Language.vi => "Áo ghi lê",
        Language.cs => "Vesta",
        Language.el => "Γιλέκο",
        Language.uk => "Жилет",
        Language.hr => "Prsluk",
        Language.ja => "ベスト", // or "チョッキ" (chokki)
        Language.pl => "Kamizelka",
        Language.pt => "Colete",
        Language.ko => "조끼",
        Language.ur => "واسکٹ",
        Language.bg => "Жилетка",
        Language.af => "Onderbaadjie", // More of a waistcoat, "Vest" can be used
        Language.hi => "बनियान", // More like undershirt, वास्कट (vaaskat) for outer vest
      },
      Category.headProtection =>
      switch (language) {
        Language.de => "Kopfschutz",
        Language.en => "Head Protection",
        Language.fr => "Protection de la tête",
        Language.it => "Protezione della testa",
        Language.es => "Protección para la cabeza",
        Language.nl => "Hoofdbescherming",
        Language.ru => "Защита головы",
        Language.tr => "Baş koruması",
        Language.no => "Hodevern",
        Language.da => "Hovedværn",
        Language.sv => "Huvudskydd",
        Language.ar => "حماية الرأس",
        Language.zh => "头部防护",
        Language.th => "อุปกรณ์ป้องกันศีรษะ",
        Language.vi => "Bảo vệ đầu",
        Language.cs => "Ochrana hlavy",
        Language.el => "Προστασία κεφαλής",
        Language.uk => "Захист голови",
        Language.hr => "Zaštita za glavu",
        Language.ja => "頭部保護具",
        Language.pl => "Ochrona głowy",
        Language.pt => "Proteção para a cabeça",
        Language.ko => "머리 보호",
        Language.ur => "سر کا تحفظ",
        Language.bg => "Защита на главата",
        Language.af => "Kopbeskerming",
        Language.hi => "सिर की सुरक्षा",
      },
      Category.eyeProtection =>
      switch (language) {
        Language.de => "Augenschutz",
        Language.en => "Eye Protection",
        Language.fr => "Protection des yeux",
        Language.it => "Protezione degli occhi",
        Language.es => "Protección ocular",
        Language.nl => "Oogbescherming",
        Language.ru => "Защита глаз",
        Language.tr => "Göz koruması",
        Language.no => "Øyevern",
        Language.da => "Øjenværn",
        Language.sv => "Ögonskydd",
        Language.ar => "حماية العين",
        Language.zh => "眼部防护",
        Language.th => "อุปกรณ์ป้องกันดวงตา",
        Language.vi => "Bảo vệ mắt",
        Language.cs => "Ochrana očí",
        Language.el => "Προστασία ματιών",
        Language.uk => "Захист очей",
        Language.hr => "Zaštita za oči",
        Language.ja => "目の保護具",
        Language.pl => "Ochrona oczu",
        Language.pt => "Proteção ocular",
        Language.ko => "눈 보호",
        Language.ur => "آنکھوں کا تحفظ",
        Language.bg => "Защита на очите",
        Language.af => "Oogbeskerming",
        Language.hi => "आंखों की सुरक्षा",
      },
      Category.sweatshirt =>
      switch (language) {
        Language.de => "Sweatshirt",
        Language.en => "Sweatshirt",
        Language.fr => "Sweat-shirt",
        Language.it => "Felpa",
        Language.es => "Sudadera",
        Language.nl => "Sweater",
        Language.ru => "Свитшот", // or Толстовка
        Language.tr => "Sweatshirt",
        Language.no => "Genser", // General term for sweater/jumper
        Language.da => "Sweatshirt",
        Language.sv => "Tröja", // General term, specifically "Sweatshirt" is also used
        Language.ar => "سويت شيرت",
        Language.zh => "运动衫",
        Language.th => "เสื้อสเวตเตอร์",
        Language.vi => "Áo nỉ",
        Language.cs => "Mikina",
        Language.el => "Φούτερ",
        Language.uk => "Світшот",
        Language.hr => "Dukserica",
        Language.ja => "スウェットシャツ",
        Language.pl => "Bluza", // General term for sweatshirt/hoodie
        Language.pt => "Moletom",
        Language.ko => "스웨트셔츠",
        Language.ur => "سویٹ شرٹ",
        Language.bg => "Суитшърт",
        Language.af => "Sweetpakbaadjie", // More like tracksuit top, "Sweater" is common
        Language.hi => "स्वेटशर्ट",
      },
      Category.pkaClothing =>
      switch (language) {
      // Assuming PKA refers to professional/work clothing
        Language.de => "Berufsbekleidung", // Professional clothing
        Language.en => "PKA Clothing", // Or "Professional Workwear" if PKA means that
        Language.fr => "Vêtements professionnels", // Professional clothing
        Language.it => "Abbigliamento da lavoro", // Workwear
        Language.es => "Ropa de trabajo", // Workwear
        Language.nl => "Bedrijfskleding", // Corporate or work clothing
        Language.ru => "Спецодежда", // Workwear/Special clothing
        Language.tr => "İş elbisesi", // Workwear
        Language.no => "Arbeidstøy", // Workwear
        Language.da => "Arbejdstøj", // Workwear
        Language.sv => "Arbetskläder", // Workwear
        Language.ar => "ملابس مهنية", // Professional clothing
        Language.zh => "职业服装", // Professional clothing
        Language.th => "ชุดทำงาน", // Workwear
        Language.vi => "Quần áo bảo hộ lao động", // Labor protection clothing
        Language.cs => "Pracovní oděvy", // Work clothing
        Language.el => "Επαγγελματική ενδυμασία", // Professional attire
        Language.uk => "Спецодяг", // Workwear
        Language.hr => "Radna odjeća", // Work clothing
        Language.ja => "作業服", // Work clothes
        Language.pl => "Odzież robocza", // Work clothing
        Language.pt => "Roupa de trabalho", // Workwear
        Language.ko => "작업복", // Work clothes
        Language.ur => "پیشہ ورانہ لباس", // Professional clothing
        Language.bg => "Работно облекло", // Work clothing
        Language.af => "Werkklere", // Workwear
        Language.hi => "पेशेवर कपड़े", // Professional clothes
      },
      Category.trousers =>
      switch (language) {
        Language.de => "Hosen",
        Language.en => "Trousers",
        Language.fr => "Pantalons",
        Language.it => "Pantaloni",
        Language.es => "Pantalones",
        Language.nl => "Broeken",
        Language.ru => "Брюки",
        Language.tr => "Pantolon",
        Language.no => "Bukser",
        Language.da => "Bukser",
        Language.sv => "Byxor",
        Language.ar => "سراويل",
        Language.zh => "裤子",
        Language.th => "กางเกง",
        Language.vi => "Quần dài",
        Language.cs => "Kalhoty",
        Language.el => "Παντελόνι",
        Language.uk => "Штани",
        Language.hr => "Hlače",
        Language.ja => "ズボン",
        Language.pl => "Spodnie",
        Language.pt => "Calças",
        Language.ko => "바지",
        Language.ur => "پتلون",
        Language.bg => "Панталони",
        Language.af => "Broek",
        Language.hi => "पतलून",
      },
      Category.kneePads =>
      switch (language) {
        Language.de => "Knieschützer",
        Language.en => "Knee Pads",
        Language.fr => "Genouillères",
        Language.it => "Ginocchiere",
        Language.es => "Rodilleras",
        Language.nl => "Kniebeschermers",
        Language.ru => "Наколенники",
        Language.tr => "Dizlik",
        Language.no => "Knebeskyttere",
        Language.da => "Knæbeskyttere",
        Language.sv => "Knäskydd",
        Language.ar => "واقيات الركبة",
        Language.zh => "护膝",
        Language.th => "สนับเข่า",
        Language.vi => "Đệm đầu gối",
        Language.cs => "Nákoleníky",
        Language.el => "Επιγονατίδες",
        Language.uk => "Наколінники",
        Language.hr => "Štitnici za koljena",
        Language.ja => "膝パッド",
        Language.pl => "Nakolanniki",
        Language.pt => "Joelheiras",
        Language.ko => "무릎 보호대",
        Language.ur => "گھٹنے کے پیڈ",
        Language.bg => "Наколенки",
        Language.af => "Kniekussings",
        Language.hi => "घुटने के पैड",
      },
      Category.clothing =>
      switch (language) {
        Language.de => "Kleidung",
        Language.en => "Clothing",
        Language.fr => "Vêtements",
        Language.it => "Abbigliamento",
        Language.es => "Ropa",
        Language.nl => "Kleding",
        Language.ru => "Одежда",
        Language.tr => "Giyim",
        Language.no => "Klær",
        Language.da => "Tøj",
        Language.sv => "Kläder",
        Language.ar => "ملابس",
        Language.zh => "服装",
        Language.th => "เสื้อผ้า",
        Language.vi => "Quần áo",
        Language.cs => "Oblečení",
        Language.el => "Ρούχα",
        Language.uk => "Одяг",
        Language.hr => "Odjeća",
        Language.ja => "衣類",
        Language.pl => "Odzież",
        Language.pt => "Roupa", // or "Vestuário"
        Language.ko => "의류",
        Language.ur => "کپڑے",
        Language.bg => "Облекло",
        Language.af => "Klere",
        Language.hi => "कपड़े",
      },
      Category.tShirt =>
      switch (language) {
        Language.de => "T-Shirt",
        Language.en => "T-Shirt",
        Language.fr => "T-shirt",
        Language.it => "Maglietta", // T-shirt is also common
        Language.es => "Camiseta",
        Language.nl => "T-shirt",
        Language.ru => "Футболка",
        Language.tr => "Tişört",
        Language.no => "T-skjorte",
        Language.da => "T-shirt",
        Language.sv => "T-shirt",
        Language.ar => "تي شيرت",
        Language.zh => "T恤",
        Language.th => "เสื้อยืด",
        Language.vi => "Áo thun",
        Language.cs => "Tričko",
        Language.el => " μπλουζάκι (T-shirt)",
        Language.uk => "Футболка",
        Language.hr => "Majica kratkih rukava", // "Majica" is general shirt
        Language.ja => "Tシャツ",
        Language.pl => "Koszulka", // General term, "T-shirt" is also common
        Language.pt => "Camiseta",
        Language.ko => "티셔츠",
        Language.ur => "ٹی شرٹ",
        Language.bg => "Тениска",
        Language.af => "T-hemp",
        Language.hi => "टी-शर्ट",
      },
      Category.bibPants =>
      switch (language) {
        Language.de => "Latzhose",
        Language.en => "Bib Pants",
        Language.fr => "Salopette",
        Language.it => "Salopette",
        Language.es => "Peto", // or "Pantalones de peto"
        Language.nl => "Tuinbroek",
        Language.ru => "Полукомбинезон", // More specific than just overalls
        Language.tr => "Salopet",
        Language.no => "Snekkerbukse",
        Language.da => "Snedkerbukser", // Carpenter pants, close to bib pants
        Language.sv => "Hängselbyxor",
        Language.ar => "بنطلون بحمالات صدرية", // Lit. trousers with a bib part
        Language.zh => "背带裤",
        Language.th => "กางเกงเอี๊ยม",
        Language.vi => "Quần yếm có нагрудник",
        Language.cs => "Kalhoty s laclem",
        Language.el => "Σαλιάρα παντελόνι",
        Language.uk => "Напівкомбінезон",
        Language.hr => "Hlače s naramenicama", // or "Tregerice"
        Language.ja => "ビブパンツ", // or オーバーオール (overall, can be used)
        Language.pl => "Spodnie na szelkach", // or "Ogrodniczki"
        Language.pt => "Jardineiras", // or "Calças com peitilho"
        Language.ko => "멜빵바지",
        Language.ur => "بِب پینٹ",
        Language.bg => "Полугащеризон",
        Language.af => "Oorbroek", // Can also mean overalls
        Language.hi => "बिब पैंट",
      },
      Category.suspenders =>
      switch (language) {
        Language.de => "Hosenträger",
        Language.en => "Suspenders",
        Language.fr => "Bretelles",
        Language.it => "Bretelle",
        Language.es => "Tirantes",
        Language.nl => "Bretels",
        Language.ru => "Подтяжки",
        Language.tr => "Pantolon askısı",
        Language.no => "Bukseseler",
        Language.da => "Seler",
        Language.sv => "Hängslen",
        Language.ar => "حمالات بنطلون",
        Language.zh => "吊裤带",
        Language.th => "สายเอี๊ยม",
        Language.vi => "Dây đeo quần",
        Language.cs => "Šle", // or "Kšandy"
        Language.el => "Τιράντες",
        Language.uk => "Підтяжки",
        Language.hr => "Naramenice za hlače", // or "Tregeri"
        Language.ja => "サスペンダー",
        Language.pl => "Szelki",
        Language.pt => "Suspensórios",
        Language.ko => "멜빵",
        Language.ur => "سسپینڈرز",
        Language.bg => "Тиранти",
        Language.af => "Kruisbande",
        Language.hi => "सस्पेंडर्स",
      },
      Category.forstschutz => switch(language) {
        Language.de => "Forstschutz",
        Language.en => "Forestry Protection",
        Language.fr => "Protection forestière",
        Language.it => "Protezione forestale",
        Language.es => "Protección forestal",
        Language.nl => "Bosbouw bescherming",
        Language.ru => "Защита лесоводства",
        Language.tr => "Ormancılık koruması",
        Language.no => "Skogbruksbeskyttelse",
        Language.da => "Skovbrugsbeskyttelse",
        Language.sv => "Skogsbruksskydd",
        Language.ar => "حماية الغابات",
        Language.zh => "林业防护",
        Language.th => "การป้องกันป่าไม้",
        Language.vi => "Bảo hộ lâm nghiệp",
        Language.cs => "Lesní ochrana",
        Language.el => "Προστασία δασοκομίας",
        Language.uk => "Захист лісового господарства",
        Language.hr => "Zaštita šumarstva",
        Language.ja => "林業保護",
        Language.pl => "Ochrona leśna",
        Language.pt => "Proteção florestal",
        Language.ko => "산림 보호",
        Language.ur => "جنگلات کا تحفظ",
        Language.bg => "Горска защита",
        Language.af => "Bosboubeskerming",
        Language.hi => "वानिकी सुरक्षा",
      },
      Category.handschuhe => switch(language) {
        Language.de => "Handschuhe",
        Language.en => "Gloves",
        Language.fr => "Gants",
        Language.it => "Guanti",
        Language.es => "Guantes",
        Language.nl => "Handschoenen",
        Language.ru => "Перчатки",
        Language.tr => "Eldivenler",
        Language.no => "Hansker",
        Language.da => "Handsker",
        Language.sv => "Handskar",
        Language.ar => "قفازات",
        Language.zh => "手套",
        Language.th => "ถุงมือ",
        Language.vi => "Găng tay",
        Language.cs => "Rukavice",
        Language.el => "Γάντια",
        Language.uk => "Рукавички",
        Language.hr => "Rukavice",
        Language.ja => "手袋",
        Language.pl => "Rękawiczki",
        Language.pt => "Luvas",
        Language.ko => "장갑",
        Language.ur => "دستانے",
        Language.bg => "Ръкавици",
        Language.af => "Handskoene",
        Language.hi => "दस्ताने",
      },
      Category.knieschutz => switch(language) {
        Language.de => "Knieschutz",
        Language.en => "Knee Protection",
        Language.fr => "Protection des genoux",
        Language.it => "Protezione ginocchia",
        Language.es => "Protección de rodillas",
        Language.nl => "Kniebescherming",
        Language.ru => "Защита коленей",
        Language.tr => "Diz koruyucu",
        Language.no => "Knebeskyttelse",
        Language.da => "Knæbeskyttelse",
        Language.sv => "Knäskydd",
        Language.ar => "حماية الركبة",
        Language.zh => "膝部防护",
        Language.th => "การป้องกันเข่า",
        Language.vi => "Bảo hộ đầu gối",
        Language.cs => "Ochrana kolen",
        Language.el => "Προστασία γονάτων",
        Language.uk => "Захист колін",
        Language.hr => "Zaštita koljena",
        Language.ja => "膝保護具",
        Language.pl => "Ochraniacze na kolana",
        Language.pt => "Proteção de joelhos",
        Language.ko => "무릎 보호대",
        Language.ur => "گھٹنے کی حفاظت",
        Language.bg => "Защита на коленете",
        Language.af => "Kniebeskerming",
        Language.hi => "घुटने की सुरक्षा",
      },
      Category.masken => switch(language) {
        Language.de => "Masken",
        Language.en => "Masks",
        Language.fr => "Masques",
        Language.it => "Maschere",
        Language.es => "Máscaras",
        Language.nl => "Maskers",
        Language.ru => "Маски",
        Language.tr => "Maskeler",
        Language.no => "Masker",
        Language.da => "Masker",
        Language.sv => "Masker",
        Language.ar => "أقنعة",
        Language.zh => "口罩",
        Language.th => "หน้ากาก",
        Language.vi => "Mặt nạ",
        Language.cs => "Masky",
        Language.el => "Μάσκες",
        Language.uk => "Маски",
        Language.hr => "Maske",
        Language.ja => "マスク",
        Language.pl => "Maski",
        Language.pt => "Máscaras",
        Language.ko => "마스크",
        Language.ur => "ماسک",
        Language.bg => "Маски",
        Language.af => "Maskers",
        Language.hi => "मास्क",
      },
      Category.pvcStiefel => switch(language) {
        Language.de => "PVC Stiefel",
        Language.en => "PVC Boots",
        Language.fr => "Bottes en PVC",
        Language.it => "Stivali in PVC",
        Language.es => "Botas de PVC",
        Language.nl => "PVC Laarzen",
        Language.ru => "Сапоги ПВХ",
        Language.tr => "PVC Çizmeler",
        Language.no => "PVC Støvler",
        Language.da => "PVC Støvler",
        Language.sv => "PVC-stövlar",
        Language.ar => "أحذية بلاستيكية",
        Language.zh => "PVC靴",
        Language.th => "รองเท้าบูท PVC",
        Language.vi => "Ủng PVC",
        Language.cs => "PVC holínky",
        Language.el => "Μπότες PVC",
        Language.uk => "Чоботи ПВХ",
        Language.hr => "PVC Čizme",
        Language.ja => "PVCブーツ",
        Language.pl => "Kalosze PCV",
        Language.pt => "Botas de PVC",
        Language.ko => "PVC 부츠",
        Language.ur => "پی وی سی جوتے",
        Language.bg => "PVC Ботуши",
        Language.af => "PVC stewels",
        Language.hi => "पीवीसी जूते",
      },
      Category.regenkleidung => switch(language) {
        Language.de => "Regenkleidung",
        Language.en => "Rainwear",
        Language.fr => "Vêtements de pluie",
        Language.it => "Abbigliamento antipioggia",
        Language.es => "Ropa de lluvia",
        Language.nl => "Regenkleding",
        Language.ru => "Дождевая одежда",
        Language.tr => "Yağmurluk",
        Language.no => "Regntøy",
        Language.da => "Regntøj",
        Language.sv => "Regnkläder",
        Language.ar => "ملابس المطر",
        Language.zh => "雨衣",
        Language.th => "ชุดกันฝน",
        Language.vi => "Quần áo mưa",
        Language.cs => "Pláštěnky",
        Language.el => "Αδιάβροχα",
        Language.uk => "Дощовий одяг",
        Language.hr => "Kišna odjeća",
        Language.ja => "レインウェア",
        Language.pl => "Odzież przeciwdeszczowa",
        Language.pt => "Roupa de chuva",
        Language.ko => "레인웨어",
        Language.ur => "بارش کا لباس",
        Language.bg => "Дъждобран",
        Language.af => "Reënklere",
        Language.hi => "रेनवियर",
      },
      Category.warnschutzkleidung => switch(language) {
        Language.de => "Warnschutzkleidung",
        Language.en => "Warning Protective Clothing",
        Language.fr => "Vêtements de protection à haute visibilité",
        Language.it => "Abbigliamento protettivo di avvertimento",
        Language.es => "Ropa de protección de advertencia",
        Language.nl => "Waarschuwingskleding",
        Language.ru => "Предупреждающая защитная одежда",
        Language.tr => "Uyarıcı Koruyucu Giysi",
        Language.no => "Varselsklær",
        Language.da => "Advarselsbeklædning",
        Language.sv => "Varningskläder",
        Language.ar => "ملابس الحماية التحذيرية",
        Language.zh => "警示防护服",
        Language.th => "เสื้อผ้าป้องกันการเตือน",
        Language.vi => "Quần áo bảo hộ cảnh báo",
        Language.cs => "Výstražné ochranné oděvy",
        Language.el => "Προστατευτικά ρούχα προειδοποίησης",
        Language.uk => "Попереджувальний захисний одяг",
        Language.hr => "Upozoravajuća zaštitna odjeća",
        Language.ja => "警告保護服",
        Language.pl => "Odzież ostrzegawcza",
        Language.pt => "Vestuário de proteção de aviso",
        Language.ko => "경고 보호복",
        Language.ur => "انتباہی حفاظتی لباس",
        Language.bg => "Предупредително защитно облекло",
        Language.af => "Waarskuwingsbeskermende klere",
        Language.hi => "चेतावनी सुरक्षात्मक कपड़े",
      },
       Category.einwegbekleidung => switch (language) {
         Language.de => "Hosenträger",
         Language.en => "Suspenders",
         Language.fr => "Bretelles",
         Language.it => "Bretelle",
         Language.es => "Tirantes",
         Language.nl => "Bretels",
         Language.ru => "Подтяжки",
         Language.tr => "Pantolon askısı",
         Language.no => "Bukseseler",
         Language.da => "Seler",
         Language.sv => "Hängslen",
         Language.ar => "حمالات بنطلون",
         Language.zh => "吊裤带",
         Language.th => "สายเอี๊ยม",
         Language.vi => "Dây đeo quần",
         Language.cs => "Šle", // or "Kšandy"
         Language.el => "Τιράντες",
         Language.uk => "Підтяжки",
         Language.hr => "Naramenice za hlače", // or "Tregeri"
         Language.ja => "サスペンダー",
         Language.pl => "Szelki",
         Language.pt => "Suspensórios",
         Language.ko => "멜빵",
         Language.ur => "سسپینڈرز",
         Language.bg => "Тиранти",
         Language.af => "Kruisbande",
         Language.hi => "सस्पेंडर्स",
       },
      Category.shirts => switch (language) {
        Language.de => "Shirts",
        Language.en => "Shirts",
        Language.fr => "Chemises",
        Language.it => "Camicie",
        Language.es => "Camisas",
        Language.nl => "Shirts",
        Language.ru => "Рубашки",
        Language.tr => "Gömlekler",
        Language.no => "Skjorter",
        Language.da => "Skjorter",
        Language.sv => "Skjortor",
        Language.ar => "قمصان",
        Language.zh => "衬衫",
        Language.th => "เสื้อเชิ้ต",
        Language.vi => "Áo sơ mi",
        Language.cs => "Košile",
        Language.el => "Πουκάμισα",
        Language.uk => "Сорочки",
        Language.hr => "Košulje",
        Language.ja => "シャツ",
        Language.pl => "Koszule",
        Language.pt => "Camisas",
        Language.ko => "셔츠",
        Language.ur => "شرٹس",
        Language.bg => "Ризи",
        Language.af => "Hemde",
        Language.hi => "शर्ट्स",
      },
      Category.schlupfkasacks => switch (language) {
        Language.de => "Schlupfkasacks",
        Language.en => "Slip-on Tunics",
        Language.fr => "Tuniques à enfiler",
        Language.it => "Casacche da infilare",
        Language.es => "Casacas sin botones",
        Language.nl => "Instapkasacks",
        Language.ru => "Туники без застежек",
        Language.tr => "Giyilebilir Tunikler",
        Language.no => "Slip-on tunikaer",
        Language.da => "Slå-om-tunikaer",
        Language.sv => "Slip-on tunikor",
        Language.ar => "سترات قابلة للانزلاق",
        Language.zh => "套头衫",
        Language.th => "เสื้อคลุมแบบสวม",
        Language.vi => "Áo khoác chui đầu",
        Language.cs => "Nátělníky",
        Language.el => "Τουνίκ με άνοιγμα",
        Language.uk => "Туніки",
        Language.hr => "Tunike na navlačenje",
        Language.ja => "スリップオンカサック",
        Language.pl => "Tuniki wkładane przez głowę",
        Language.pt => "Batas de vestir",
        Language.ko => "슬립온 튜닉",
        Language.ur => "سلپ آن ٹیونِکس",
        Language.bg => "Плъзгащи се туники",
        Language.af => "Sluipkasakke",
        Language.hi => "स्लिप-ऑन ट्यूनिक्स",
      },
      Category.poloshirts => switch (language) {
        Language.de => "Poloshirts",
        Language.en => "Polo Shirts",
        Language.fr => "Polos",
        Language.it => "Polo",
        Language.es => "Polos",
        Language.nl => "Poloshirts",
        Language.ru => "Поло",
        Language.tr => "Polo Tişörtler",
        Language.no => "Polo Skjorter",
        Language.da => "Polo T-shirts",
        Language.sv => "Pikétröjor",
        Language.ar => "قمصان بولو",
        Language.zh => "Polo衫",
        Language.th => "เสื้อโปโล",
        Language.vi => "Áo polo",
        Language.cs => "Polokošile",
        Language.el => "Μπλουζάκια πόλο",
        Language.uk => "Поло",
        Language.hr => "Polo majice",
        Language.ja => "ポロシャツ",
        Language.pl => "Koszulki polo",
        Language.pt => "Camisas polo",
        Language.ko => "폴로 셔츠",
        Language.ur => "پولو شرٹس",
        Language.bg => "Поло тениски",
        Language.af => "Polo hemde",
        Language.hi => "पोलो शर्ट्स",
      },
      Category.hoodyjacken => switch (language) {
        Language.de => "Hoodyjacken",
        Language.en => "Hooded Jackets",
        Language.fr => "Vestes à capuche",
        Language.it => "Giacche con cappuccio",
        Language.es => "Chaquetas con capucha",
        Language.nl => "Hoody jassen",
        Language.ru => "Куртки с капюшоном",
        Language.tr => "Kapüşonlu Ceketler",
        Language.no => "Hettejakker",
        Language.da => "Hættejakker",
        Language.sv => "Hoodie-jackor",
        Language.ar => "جاكيتات بغطاء للرأس",
        Language.zh => "连帽夹克",
        Language.th => "เสื้อแจ็คเก็ตมีฮู้ด",
        Language.vi => "Áo khoác có mũ",
        Language.cs => "Mikiny s kapucí",
        Language.el => "Μπουφάν με κουκούλα",
        Language.uk => "Куртки з капюшоном",
        Language.hr => "Jakne s kapuljačom",
        Language.ja => "フーディージャケット",
        Language.pl => "Kurtki z kapturem",
        Language.pt => "Casacos com capuz",
        Language.ko => "후드 재킷",
        Language.ur => "ہڈڈ جیکٹس",
        Language.bg => "Якета с качулка",
        Language.af => "Hoody baadjies",
        Language.hi => "हुडी जैकेट",
      },
      Category.sweatjacken => switch (language) {
        Language.de => "Sweatjacken",
        Language.en => "Sweatjackets",
        Language.fr => "Vestes de survêtement",
        Language.it => "Giacche in felpa",
        Language.es => "Chaquetas de chándal",
        Language.nl => "Sweatjacks",
        Language.ru => "Толстовки",
        Language.tr => "Sweatshirt Ceketler",
        Language.no => "Treningsjakker",
        Language.da => "Sweatjakker",
        Language.sv => "Sweatjackor",
        Language.ar => "جاكيتات رياضية",
        Language.zh => "运动衫",
        Language.th => "เสื้อสเวตเตอร์",
        Language.vi => "Áo khoác nỉ",
        Language.cs => "Mikiny na zip",
        Language.el => "Φούτερ",
        Language.uk => "Світшоти",
        Language.hr => "Dukserice",
        Language.ja => "スウェットジャケット",
        Language.pl => "Bluzy rozpinane",
        Language.pt => "Casacos de moletom",
        Language.ko => "스웨트 재킷",
        Language.ur => "سویٹ جیکٹس",
        Language.bg => "Суитшърти",
        Language.af => "Sweetjasse",
        Language.hi => "स्वेटजैकेट्स",
      },
    };
  }
}
