import 'package:easywear_models/easywear_models.dart';

final Map<Category, Set<Category>> categoryHierarchy = {
  Category.accessoires: {
    Category.halstuecher,
    Category.hosentraeger,
    Category.aermelbaender,
    Category.handschuhe,
    Category.fliegen,
    Category.krawatten,
    Category.friseurumhaenge,
    Category.geschirrtuecher,
    Category.kassierhalfter,
    Category.kugelknopf,
    Category.knopfleisten,
    Category.geldboersen,
    Category.passiertuecher,
  },
  Category.schuerzen: {
    Category.bistroschuerzen,
    Category.latzschuerzen,
    Category.vorbinder,
  },
  Category.hemden: {
    Category.langaermligeHemden,
    Category.kurzaermeligeHemden,
  },
  Category.blusen: {
    Category.langaermligeBlusen,
    Category.kurzaermeligeBlusen,
  },
  Category.hosen: {},
  Category.roecke: {},
  Category.jacken: {
    Category.kochjacken,
    Category.softshelljacken,
    Category.fleecejacken,
    Category.hybridjacken,
  },
  Category.maentel: {},
  Category.shirts: {
    Category.poloshirts,
    Category.tShirts,
    Category.langaermligeShirts,
  },
  Category.schuhe: {
    Category.berufsschuhe,
    Category.sicherheitsschuhe,
  },
  Category.westen: {
    Category.kellnerwesten,
    Category.softshellwesten,
  },
  Category.kopfbedeckungen: {
    Category.barettmuetzen,
    Category.kochmuetzen,
    Category.bandanas,
    Category.fleischermuetzen,
    Category.basecaps,
  },
  Category.kasacks: {},
};

enum Category {
  // Main Categories
  accessoires,
  schuerzen,
  hemden,
  blusen,
  hosen,
  roecke,
  jacken,
  maentel,
  shirts,
  schuhe,
  westen,
  kopfbedeckungen,
  kasacks,

  // Accessoires Subcategories
  halstuecher,
  hosentraeger,
  aermelbaender,
  handschuhe,
  fliegen,
  krawatten,
  friseurumhaenge,
  geschirrtuecher,
  kassierhalfter,
  kugelknopf,
  knopfleisten,
  geldboersen,
  passiertuecher,

  // Schürzen Subcategories
  bistroschuerzen,
  latzschuerzen,
  vorbinder,

  // Hemden Subcategories
  langaermligeHemden,
  kurzaermeligeHemden,

  // Blusen Subcategories
  langaermligeBlusen,
  kurzaermeligeBlusen,

  // Jacken Subcategories
  kochjacken,
  softshelljacken,
  fleecejacken,
  hybridjacken,

  // Shirts Subcategories
  poloshirts,
  tShirts,
  langaermligeShirts,

  // Schuhe Subcategories
  berufsschuhe,
  sicherheitsschuhe,

  // Westen Subcategories
  kellnerwesten,
  softshellwesten,

  // Kopfbedeckungen Subcategories
  barettmuetzen,
  kochmuetzen,
  bandanas,
  fleischermuetzen,
  basecaps;

  static Category fromString(String s) => Category.values.firstWhere((v) => v.string == s);

// String uiText(Language language) {
//   return switch (this) {
//     Category.accessories => switch (language) {
//         Language.de => "Zubehör",
//         Language.en => "Accessories",
//         Language.fr => "Accessoires",
//         Language.it => "Accessori",
//         Language.es => "Accesorios",
//         Language.nl => "Accessoires",
//         Language.ru => "Аксессуары",
//         Language.tr => "Aksesuarlar",
//         Language.no => "Tilbehør",
//         Language.da => "Tilbehør",
//         Language.sv => "Accessoarer",
//         Language.ar => "إكسسوارات",
//         Language.zh => "饰品",
//         Language.th => "เครื่องประดับ",
//         Language.vi => "Phụ kiện",
//         Language.cs => "Doplňky",
//         Language.el => "Αξεσουάρ",
//         Language.uk => "Аксесуари",
//         Language.hr => "Pribor",
//         Language.ja => "アクセサリー",
//         Language.pl => "Akcesoria",
//         Language.pt => "Acessórios",
//         Language.ko => "액세서리",
//         Language.ur => "لوازمات",
//         Language.bg => "Аксесоари",
//         Language.af => "Toebehore",
//         Language.hi => "सहायक उपकरण",
//       },
//     Category.miscellaneous => switch (language) {
//         Language.de => "Sonstiges",
//         Language.en => "Miscellaneous",
//         Language.fr => "Divers",
//         Language.it => "Varie",
//         Language.es => "Miscelánea",
//         Language.nl => "Diversen",
//         Language.ru => "Разное",
//         Language.tr => "Çeşitli",
//         Language.no => "Diverse",
//         Language.da => "Diverse",
//         Language.sv => "Diverse",
//         Language.ar => "متنوعات",
//         Language.zh => "杂项",
//         Language.th => "เบ็ดเตล็ด",
//         Language.vi => "Linh tinh",
//         Language.cs => "Různé",
//         Language.el => "Διάφορα",
//         Language.uk => "Різне",
//         Language.hr => "Razno",
//         Language.ja => "その他",
//         Language.pl => "Różne",
//         Language.pt => "Diversos",
//         Language.ko => "기타",
//         Language.ur => "متفرق",
//         Language.bg => "Разни",
//         Language.af => "Diverse",
//         Language.hi => "विविध",
//       },
//     Category.shirt => switch (language) {
//         Language.de => "Hemd",
//         Language.en => "Shirt",
//         Language.fr => "Chemise",
//         Language.it => "Camicia",
//         Language.es => "Camisa",
//         Language.nl => "Overhemd",
//         Language.ru => "Рубашка",
//         Language.tr => "Gömlek",
//         Language.no => "Skjorte",
//         Language.da => "Skjorte",
//         Language.sv => "Skjorta",
//         Language.ar => "قميص",
//         Language.zh => "衬衫",
//         Language.th => "เสื้อเชิ้ต",
//         Language.vi => "Áo sơ mi",
//         Language.cs => "Košile",
//         Language.el => "Πουκάμισο",
//         Language.uk => "Сорочка",
//         Language.hr => "Košulja",
//         Language.ja => "シャツ",
//         Language.pl => "Koszula",
//         Language.pt => "Camisa",
//         Language.ko => "셔츠",
//         Language.ur => "قمیض",
//         Language.bg => "Риза",
//         Language.af => "Hemp",
//         Language.hi => "शर्ट",
//       },
//     Category.disposableClothing => switch (language) {
//         Language.de => "Einwegkleidung",
//         Language.en => "Disposable Clothing",
//         Language.fr => "Vêtements jetables",
//         Language.it => "Abbigliamento monouso",
//         Language.es => "Ropa desechable",
//         Language.nl => "Wegwerpkleding",
//         Language.ru => "Одноразовая одежда",
//         Language.tr => "Tek kullanımlık giysi",
//         Language.no => "Engangsklær",
//         Language.da => "Engangsbeklædning",
//         Language.sv => "Engångskläder",
//         Language.ar => "ملابس يمكن التخلص منها",
//         Language.zh => "一次性服装",
//         Language.th => "เสื้อผ้าใช้แล้วทิ้ง",
//         Language.vi => "Quần áo dùng một lần",
//         Language.cs => "Jednorázové oděvy",
//         Language.el => "Ρούχα μιας χρήσης",
//         Language.uk => "Одноразовий одяг",
//         Language.hr => "Jednokratna odjeća",
//         Language.ja => "使い捨て衣類",
//         Language.pl => "Odzież jednorazowa",
//         Language.pt => "Roupa descartável",
//         Language.ko => "일회용 의류",
//         Language.ur => "ڈسپوزایبل لباس",
//         Language.bg => "Облекло за еднократна употреба",
//         Language.af => "Weggooibare klere",
//         Language.hi => "डिस्पोजेबल कपड़े",
//       },
//     Category.jacket => switch (language) {
//         Language.de => "Jacke",
//         Language.en => "Jacket",
//         Language.fr => "Veste",
//         Language.it => "Giacca",
//         Language.es => "Chaqueta",
//         Language.nl => "Jas",
//         Language.ru => "Куртка",
//         Language.tr => "Ceket",
//         Language.no => "Jakke",
//         Language.da => "Jakke",
//         Language.sv => "Jacka",
//         Language.ar => "سترة",
//         Language.zh => "夹克",
//         Language.th => "เสื้อแจ็คเก็ต",
//         Language.vi => "Áo khoác",
//         Language.cs => "Bunda",
//         Language.el => "Μπουφάν",
//         Language.uk => "Куртка",
//         Language.hr => "Jakna",
//         Language.ja => "ジャケット",
//         Language.pl => "Kurtka",
//         Language.pt => "Jaqueta",
//         Language.ko => "재킷",
//         Language.ur => "جیکٹ",
//         Language.bg => "Яке",
//         Language.af => "Baadjie",
//         Language.hi => "जैकेट",
//       },
//     Category.overall => switch (language) {
//         Language.de => "Overall",
//         Language.en => "Overall",
//         Language.fr => "Combinaison",
//         Language.it => "Tuta",
//         Language.es => "Mono", // or "Overol" depending on region
//         Language.nl => "Overall",
//         Language.ru => "Комбинезон",
//         Language.tr => "Tulum",
//         Language.no => "Kjeledress",
//         Language.da => "Overall", // or "Kjeldress"
//         Language.sv => "Overall",
//         Language.ar => "أفرول",
//         Language.zh => "工装裤", // More specific: 连身裤 (liánshēnkù) for coveralls
//         Language.th => "ชุดเอี๊ยม",
//         Language.vi => "Quần yếm",
//         Language.cs => "Kombinéza",
//         Language.el => "Ολόσωμη φόρμα",
//         Language.uk => "Комбінезон",
//         Language.hr => "Kombinezon",
//         Language.ja => "オーバーオール",
//         Language.pl => "Kombinezon",
//         Language.pt => "Macacão",
//         Language.ko => "오버롤",
//         Language.ur => "اوورآل",
//         Language.bg => "Гащеризон",
//         Language.af => "Oorpak",
//         Language.hi => "ओवरऑल",
//       },
//     Category.hearingProtection => switch (language) {
//         Language.de => "Gehörschutz",
//         Language.en => "Hearing Protection",
//         Language.fr => "Protection auditive",
//         Language.it => "Protezione dell'udito",
//         Language.es => "Protección auditiva",
//         Language.nl => "Gehoorbescherming",
//         Language.ru => "Средства защиты слуха",
//         Language.tr => "Kulak koruyucu",
//         Language.no => "Hørselsvern",
//         Language.da => "Høreværn",
//         Language.sv => "Hörselskydd",
//         Language.ar => "حماية السمع",
//         Language.zh => "听力保护",
//         Language.th => "อุปกรณ์ป้องกันการได้ยิน",
//         Language.vi => "Bảo vệ thính giác",
//         Language.cs => "Ochrana sluchu",
//         Language.el => "Προστασία ακοής",
//         Language.uk => "Засоби захисту слуху",
//         Language.hr => "Zaštita sluha",
//         Language.ja => "聴覚保護具",
//         Language.pl => "Ochrona słuchu",
//         Language.pt => "Proteção auditiva",
//         Language.ko => "청력 보호",
//         Language.ur => "سماعت کا تحفظ",
//         Language.bg => "Защита на слуха",
//         Language.af => "Gehoorbeskerming",
//         Language.hi => "श्रवण सुरक्षा",
//       },
//     Category.shoes => switch (language) {
//         Language.de => "Schuhe",
//         Language.en => "Shoes",
//         Language.fr => "Chaussures",
//         Language.it => "Scarpe",
//         Language.es => "Zapatos",
//         Language.nl => "Schoenen",
//         Language.ru => "Обувь",
//         Language.tr => "Ayakkabı",
//         Language.no => "Sko",
//         Language.da => "Sko",
//         Language.sv => "Skor",
//         Language.ar => "أحذية",
//         Language.zh => "鞋子",
//         Language.th => "รองเท้า",
//         Language.vi => "Giày",
//         Language.cs => "Boty",
//         Language.el => "Παπούτσια",
//         Language.uk => "Взуття",
//         Language.hr => "Cipele",
//         Language.ja => "靴",
//         Language.pl => "Buty",
//         Language.pt => "Sapatos",
//         Language.ko => "신발",
//         Language.ur => "جوتے",
//         Language.bg => "Обувки",
//         Language.af => "Skoene",
//         Language.hi => "जूते",
//       },
//     Category.other => switch (language) {
//         Language.de => "Andere",
//         Language.en => "Other",
//         Language.fr => "Autre",
//         Language.it => "Altro",
//         Language.es => "Otro",
//         Language.nl => "Overig",
//         Language.ru => "Другое",
//         Language.tr => "Diğer",
//         Language.no => "Annet",
//         Language.da => "Andet",
//         Language.sv => "Övrigt",
//         Language.ar => "آخر",
//         Language.zh => "其他",
//         Language.th => "อื่น ๆ",
//         Language.vi => "Khác",
//         Language.cs => "Ostatní",
//         Language.el => "Άλλο",
//         Language.uk => "Інше",
//         Language.hr => "Ostalo",
//         Language.ja => "その他",
//         Language.pl => "Inne",
//         Language.pt => "Outro",
//         Language.ko => "기타",
//         Language.ur => "دیگر",
//         Language.bg => "Други",
//         Language.af => "Ander",
//         Language.hi => "अन्य",
//       },
//     Category.masks => switch (language) {
//         Language.de => "Masken",
//         Language.en => "Masks",
//         Language.fr => "Masques",
//         Language.it => "Maschere",
//         Language.es => "Mascarillas",
//         Language.nl => "Maskers",
//         Language.ru => "Маски",
//         Language.tr => "Maskeler",
//         Language.no => "Masker",
//         Language.da => "Masker",
//         Language.sv => "Masker",
//         Language.ar => "أقنعة",
//         Language.zh => "口罩",
//         Language.th => "หน้ากาก",
//         Language.vi => "Khẩu trang",
//         Language.cs => "Masky",
//         Language.el => "Μάσκες",
//         Language.uk => "Маски",
//         Language.hr => "Maske",
//         Language.ja => "マスク",
//         Language.pl => "Maski",
//         Language.pt => "Máscaras",
//         Language.ko => "마스크",
//         Language.ur => "ماسک",
//         Language.bg => "Маски",
//         Language.af => "Maskers",
//         Language.hi => "मास्क",
//       },
//     Category.gloves => switch (language) {
//         Language.de => "Handschuhe",
//         Language.en => "Gloves",
//         Language.fr => "Gants",
//         Language.it => "Guanti",
//         Language.es => "Guantes",
//         Language.nl => "Handschoenen",
//         Language.ru => "Перчатки",
//         Language.tr => "Eldivenler",
//         Language.no => "Hansker",
//         Language.da => "Handsker",
//         Language.sv => "Handskar",
//         Language.ar => "قفازات",
//         Language.zh => "手套",
//         Language.th => "ถุงมือ",
//         Language.vi => "Găng tay",
//         Language.cs => "Rukavice",
//         Language.el => "Γάντια",
//         Language.uk => "Рукавички",
//         Language.hr => "Rukavice",
//         Language.ja => "手袋",
//         Language.pl => "Rękawice",
//         Language.pt => "Luvas",
//         Language.ko => "장갑",
//         Language.ur => "دستانے",
//         Language.bg => "Ръкавици",
//         Language.af => "Handskoene",
//         Language.hi => "दस्ताने",
//       },
//     Category.shorts => switch (language) {
//         Language.de => "Kurze Hosen",
//         Language.en => "Shorts",
//         Language.fr => "Shorts",
//         Language.it => "Pantaloncini",
//         Language.es => "Pantalones cortos",
//         Language.nl => "Korte broeken",
//         Language.ru => "Шорты",
//         Language.tr => "Şort",
//         Language.no => "Shorts",
//         Language.da => "Shorts",
//         Language.sv => "Shorts",
//         Language.ar => "شورت",
//         Language.zh => "短裤",
//         Language.th => "กางเกงขาสั้น",
//         Language.vi => "Quần short",
//         Language.cs => "Kraťasy",
//         Language.el => "Σορτς",
//         Language.uk => "Шорти",
//         Language.hr => "Kratke hlače",
//         Language.ja => "ショートパンツ",
//         Language.pl => "Szorty",
//         Language.pt => "Shorts", // or "Calções"
//         Language.ko => "반바지",
//         Language.ur => "شارٹس",
//         Language.bg => "Къси панталони",
//         Language.af => "Kortbroek",
//         Language.hi => "शॉर्ट्स",
//       },
//     Category.vest => switch (language) {
//         Language.de => "Weste",
//         Language.en => "Vest",
//         Language.fr => "Gilet",
//         Language.it => "Gilet", // or "Panciotto"
//         Language.es => "Chaleco",
//         Language.nl => "Vest", // Can also mean cardigan, "Gilet" is more specific for waistcoat type
//         Language.ru => "Жилет",
//         Language.tr => "Yelek",
//         Language.no => "Vest",
//         Language.da => "Vest",
//         Language.sv => "Väst",
//         Language.ar => "سترة", // Can also mean jacket, صدرية (sadria) is more specific
//         Language.zh => "背心",
//         Language.th => "เสื้อกั๊ก",
//         Language.vi => "Áo ghi lê",
//         Language.cs => "Vesta",
//         Language.el => "Γιλέκο",
//         Language.uk => "Жилет",
//         Language.hr => "Prsluk",
//         Language.ja => "ベスト", // or "チョッキ" (chokki)
//         Language.pl => "Kamizelka",
//         Language.pt => "Colete",
//         Language.ko => "조끼",
//         Language.ur => "واسکٹ",
//         Language.bg => "Жилетка",
//         Language.af => "Onderbaadjie", // More of a waistcoat, "Vest" can be used
//         Language.hi => "बनियान", // More like undershirt, वास्कट (vaaskat) for outer vest
//       },
//     Category.headProtection => switch (language) {
//         Language.de => "Kopfschutz",
//         Language.en => "Head Protection",
//         Language.fr => "Protection de la tête",
//         Language.it => "Protezione della testa",
//         Language.es => "Protección para la cabeza",
//         Language.nl => "Hoofdbescherming",
//         Language.ru => "Защита головы",
//         Language.tr => "Baş koruması",
//         Language.no => "Hodevern",
//         Language.da => "Hovedværn",
//         Language.sv => "Huvudskydd",
//         Language.ar => "حماية الرأس",
//         Language.zh => "头部防护",
//         Language.th => "อุปกรณ์ป้องกันศีรษะ",
//         Language.vi => "Bảo vệ đầu",
//         Language.cs => "Ochrana hlavy",
//         Language.el => "Προστασία κεφαλής",
//         Language.uk => "Захист голови",
//         Language.hr => "Zaštita za glavu",
//         Language.ja => "頭部保護具",
//         Language.pl => "Ochrona głowy",
//         Language.pt => "Proteção para a cabeça",
//         Language.ko => "머리 보호",
//         Language.ur => "سر کا تحفظ",
//         Language.bg => "Защита на главата",
//         Language.af => "Kopbeskerming",
//         Language.hi => "सिर की सुरक्षा",
//       },
//     Category.eyeProtection => switch (language) {
//         Language.de => "Augenschutz",
//         Language.en => "Eye Protection",
//         Language.fr => "Protection des yeux",
//         Language.it => "Protezione degli occhi",
//         Language.es => "Protección ocular",
//         Language.nl => "Oogbescherming",
//         Language.ru => "Защита глаз",
//         Language.tr => "Göz koruması",
//         Language.no => "Øyevern",
//         Language.da => "Øjenværn",
//         Language.sv => "Ögonskydd",
//         Language.ar => "حماية العين",
//         Language.zh => "眼部防护",
//         Language.th => "อุปกรณ์ป้องกันดวงตา",
//         Language.vi => "Bảo vệ mắt",
//         Language.cs => "Ochrana očí",
//         Language.el => "Προστασία ματιών",
//         Language.uk => "Захист очей",
//         Language.hr => "Zaštita za oči",
//         Language.ja => "目の保護具",
//         Language.pl => "Ochrona oczu",
//         Language.pt => "Proteção ocular",
//         Language.ko => "눈 보호",
//         Language.ur => "آنکھوں کا تحفظ",
//         Language.bg => "Защита на очите",
//         Language.af => "Oogbeskerming",
//         Language.hi => "आंखों की सुरक्षा",
//       },
//     Category.sweatshirt => switch (language) {
//         Language.de => "Sweatshirt",
//         Language.en => "Sweatshirt",
//         Language.fr => "Sweat-shirt",
//         Language.it => "Felpa",
//         Language.es => "Sudadera",
//         Language.nl => "Sweater",
//         Language.ru => "Свитшот", // or Толстовка
//         Language.tr => "Sweatshirt",
//         Language.no => "Genser", // General term for sweater/jumper
//         Language.da => "Sweatshirt",
//         Language.sv => "Tröja", // General term, specifically "Sweatshirt" is also used
//         Language.ar => "سويت شيرت",
//         Language.zh => "运动衫",
//         Language.th => "เสื้อสเวตเตอร์",
//         Language.vi => "Áo nỉ",
//         Language.cs => "Mikina",
//         Language.el => "Φούτερ",
//         Language.uk => "Світшот",
//         Language.hr => "Dukserica",
//         Language.ja => "スウェットシャツ",
//         Language.pl => "Bluza", // General term for sweatshirt/hoodie
//         Language.pt => "Moletom",
//         Language.ko => "스웨트셔츠",
//         Language.ur => "سویٹ شرٹ",
//         Language.bg => "Суитшърт",
//         Language.af => "Sweetpakbaadjie", // More like tracksuit top, "Sweater" is common
//         Language.hi => "स्वेटशर्ट",
//       },
//     Category.pkaClothing => switch (language) {
//         // Assuming PKA refers to professional/work clothing
//         Language.de => "Berufsbekleidung", // Professional clothing
//         Language.en => "PKA Clothing", // Or "Professional Workwear" if PKA means that
//         Language.fr => "Vêtements professionnels", // Professional clothing
//         Language.it => "Abbigliamento da lavoro", // Workwear
//         Language.es => "Ropa de trabajo", // Workwear
//         Language.nl => "Bedrijfskleding", // Corporate or work clothing
//         Language.ru => "Спецодежда", // Workwear/Special clothing
//         Language.tr => "İş elbisesi", // Workwear
//         Language.no => "Arbeidstøy", // Workwear
//         Language.da => "Arbejdstøj", // Workwear
//         Language.sv => "Arbetskläder", // Workwear
//         Language.ar => "ملابس مهنية", // Professional clothing
//         Language.zh => "职业服装", // Professional clothing
//         Language.th => "ชุดทำงาน", // Workwear
//         Language.vi => "Quần áo bảo hộ lao động", // Labor protection clothing
//         Language.cs => "Pracovní oděvy", // Work clothing
//         Language.el => "Επαγγελματική ενδυμασία", // Professional attire
//         Language.uk => "Спецодяг", // Workwear
//         Language.hr => "Radna odjeća", // Work clothing
//         Language.ja => "作業服", // Work clothes
//         Language.pl => "Odzież robocza", // Work clothing
//         Language.pt => "Roupa de trabalho", // Workwear
//         Language.ko => "작업복", // Work clothes
//         Language.ur => "پیشہ ورانہ لباس", // Professional clothing
//         Language.bg => "Работно облекло", // Work clothing
//         Language.af => "Werkklere", // Workwear
//         Language.hi => "पेशेवर कपड़े", // Professional clothes
//       },
//     Category.trousers => switch (language) {
//         Language.de => "Hosen",
//         Language.en => "Trousers",
//         Language.fr => "Pantalons",
//         Language.it => "Pantaloni",
//         Language.es => "Pantalones",
//         Language.nl => "Broeken",
//         Language.ru => "Брюки",
//         Language.tr => "Pantolon",
//         Language.no => "Bukser",
//         Language.da => "Bukser",
//         Language.sv => "Byxor",
//         Language.ar => "سراويل",
//         Language.zh => "裤子",
//         Language.th => "กางเกง",
//         Language.vi => "Quần dài",
//         Language.cs => "Kalhoty",
//         Language.el => "Παντελόνι",
//         Language.uk => "Штани",
//         Language.hr => "Hlače",
//         Language.ja => "ズボン",
//         Language.pl => "Spodnie",
//         Language.pt => "Calças",
//         Language.ko => "바지",
//         Language.ur => "پتلون",
//         Language.bg => "Панталони",
//         Language.af => "Broek",
//         Language.hi => "पतलून",
//       },
//     Category.kneePads => switch (language) {
//         Language.de => "Knieschützer",
//         Language.en => "Knee Pads",
//         Language.fr => "Genouillères",
//         Language.it => "Ginocchiere",
//         Language.es => "Rodilleras",
//         Language.nl => "Kniebeschermers",
//         Language.ru => "Наколенники",
//         Language.tr => "Dizlik",
//         Language.no => "Knebeskyttere",
//         Language.da => "Knæbeskyttere",
//         Language.sv => "Knäskydd",
//         Language.ar => "واقيات الركبة",
//         Language.zh => "护膝",
//         Language.th => "สนับเข่า",
//         Language.vi => "Đệm đầu gối",
//         Language.cs => "Nákoleníky",
//         Language.el => "Επιγονατίδες",
//         Language.uk => "Наколінники",
//         Language.hr => "Štitnici za koljena",
//         Language.ja => "膝パッド",
//         Language.pl => "Nakolanniki",
//         Language.pt => "Joelheiras",
//         Language.ko => "무릎 보호대",
//         Language.ur => "گھٹنے کے پیڈ",
//         Language.bg => "Наколенки",
//         Language.af => "Kniekussings",
//         Language.hi => "घुटने के पैड",
//       },
//     Category.clothing => switch (language) {
//         Language.de => "Kleidung",
//         Language.en => "Clothing",
//         Language.fr => "Vêtements",
//         Language.it => "Abbigliamento",
//         Language.es => "Ropa",
//         Language.nl => "Kleding",
//         Language.ru => "Одежда",
//         Language.tr => "Giyim",
//         Language.no => "Klær",
//         Language.da => "Tøj",
//         Language.sv => "Kläder",
//         Language.ar => "ملابس",
//         Language.zh => "服装",
//         Language.th => "เสื้อผ้า",
//         Language.vi => "Quần áo",
//         Language.cs => "Oblečení",
//         Language.el => "Ρούχα",
//         Language.uk => "Одяг",
//         Language.hr => "Odjeća",
//         Language.ja => "衣類",
//         Language.pl => "Odzież",
//         Language.pt => "Roupa", // or "Vestuário"
//         Language.ko => "의류",
//         Language.ur => "کپڑے",
//         Language.bg => "Облекло",
//         Language.af => "Klere",
//         Language.hi => "कपड़े",
//       },
//     Category.tShirt => switch (language) {
//         Language.de => "T-Shirt",
//         Language.en => "T-Shirt",
//         Language.fr => "T-shirt",
//         Language.it => "Maglietta", // T-shirt is also common
//         Language.es => "Camiseta",
//         Language.nl => "T-shirt",
//         Language.ru => "Футболка",
//         Language.tr => "Tişört",
//         Language.no => "T-skjorte",
//         Language.da => "T-shirt",
//         Language.sv => "T-shirt",
//         Language.ar => "تي شيرت",
//         Language.zh => "T恤",
//         Language.th => "เสื้อยืด",
//         Language.vi => "Áo thun",
//         Language.cs => "Tričko",
//         Language.el => " μπλουζάκι (T-shirt)",
//         Language.uk => "Футболка",
//         Language.hr => "Majica kratkih rukava", // "Majica" is general shirt
//         Language.ja => "Tシャツ",
//         Language.pl => "Koszulka", // General term, "T-shirt" is also common
//         Language.pt => "Camiseta",
//         Language.ko => "티셔츠",
//         Language.ur => "ٹی شرٹ",
//         Language.bg => "Тениска",
//         Language.af => "T-hemp",
//         Language.hi => "टी-शर्ट",
//       },
//     Category.bibPants => switch (language) {
//         Language.de => "Latzhose",
//         Language.en => "Bib Pants",
//         Language.fr => "Salopette",
//         Language.it => "Salopette",
//         Language.es => "Peto", // or "Pantalones de peto"
//         Language.nl => "Tuinbroek",
//         Language.ru => "Полукомбинезон", // More specific than just overalls
//         Language.tr => "Salopet",
//         Language.no => "Snekkerbukse",
//         Language.da => "Snedkerbukser", // Carpenter pants, close to bib pants
//         Language.sv => "Hängselbyxor",
//         Language.ar => "بنطلون بحمالات صدرية", // Lit. trousers with a bib part
//         Language.zh => "背带裤",
//         Language.th => "กางเกงเอี๊ยม",
//         Language.vi => "Quần yếm có нагрудник",
//         Language.cs => "Kalhoty s laclem",
//         Language.el => "Σαλιάρα παντελόνι",
//         Language.uk => "Напівкомбінезон",
//         Language.hr => "Hlače s naramenicama", // or "Tregerice"
//         Language.ja => "ビブパンツ", // or オーバーオール (overall, can be used)
//         Language.pl => "Spodnie na szelkach", // or "Ogrodniczki"
//         Language.pt => "Jardineiras", // or "Calças com peitilho"
//         Language.ko => "멜빵바지",
//         Language.ur => "بِب پینٹ",
//         Language.bg => "Полугащеризон",
//         Language.af => "Oorbroek", // Can also mean overalls
//         Language.hi => "बिब पैंट",
//       },
//     Category.suspenders => switch (language) {
//         Language.de => "Hosenträger",
//         Language.en => "Suspenders",
//         Language.fr => "Bretelles",
//         Language.it => "Bretelle",
//         Language.es => "Tirantes",
//         Language.nl => "Bretels",
//         Language.ru => "Подтяжки",
//         Language.tr => "Pantolon askısı",
//         Language.no => "Bukseseler",
//         Language.da => "Seler",
//         Language.sv => "Hängslen",
//         Language.ar => "حمالات بنطلون",
//         Language.zh => "吊裤带",
//         Language.th => "สายเอี๊ยม",
//         Language.vi => "Dây đeo quần",
//         Language.cs => "Šle", // or "Kšandy"
//         Language.el => "Τιράντες",
//         Language.uk => "Підтяжки",
//         Language.hr => "Naramenice za hlače", // or "Tregeri"
//         Language.ja => "サスペンダー",
//         Language.pl => "Szelki",
//         Language.pt => "Suspensórios",
//         Language.ko => "멜빵",
//         Language.ur => "سسپینڈرز",
//         Language.bg => "Тиранти",
//         Language.af => "Kruisbande",
//         Language.hi => "सस्पेंडर्स",
//       },
//   };
// }
}
