import 'package:easywear_models/easywear_models.dart';

enum Country {
  af_,
  eg_,
  al_,
  dz_,
  ad_,
  ao_,
  ag_,
  gq_,
  ar_,
  am_,
  az_,
  et_,
  au_,
  bs_,
  bh_,
  bd_,
  bb_,
  by_,
  be_,
  bz_,
  bj_,
  bt_,
  bo_,
  ba_,
  bw_,
  br_,
  bn_,
  bg_,
  bf_,
  bi_,
  cv_,
  cl_,
  cn_,
  ck_,
  cr_,
  ci_,
  dk_,
  de_,
  dm_,
  do_,
  dj_,
  ec_,
  sv_,
  er_,
  ee_,
  sz_,
  fj_,
  fi_,
  fr_,
  ga_,
  gm_,
  ge_,
  gh_,
  gd_,
  gr_,
  gt_,
  gn_,
  gw_,
  gy_,
  ht_,
  va_,
  hn_,
  in_,
  id_,
  iq_,
  ir_,
  ie_,
  is_,
  il_,
  it_,
  jm_,
  jp_,
  ye_,
  jo_,
  kh_,
  cm_,
  ca_,
  kz_,
  qa_,
  ke_,
  kg_,
  ki_,
  co_,
  km_,
  cg_,
  cd_,
  kp_,
  kr_,
  xk_,
  hr_,
  cu_,
  kw_,
  la_,
  ls_,
  lv_,
  lb_,
  lr_,
  ly_,
  li_,
  lt_,
  lu_,
  mg_,
  mw_,
  my_,
  mv_,
  ml_,
  mt_,
  ma_,
  mh_,
  mr_,
  mu_,
  mx_,
  fm_,
  md_,
  mc_,
  mn_,
  me_,
  mz_,
  mm_,
  na_,
  nr_,
  np_,
  nz_,
  ni_,
  nl_,
  ne_,
  ng_,
  nu_,
  mk_,
  no_,
  om_,
  at_,
  pk_,
  pw_,
  pa_,
  pg_,
  py_,
  pe_,
  ph_,
  pl_,
  pt_,
  rw_,
  ro_,
  ru_,
  sb_,
  zm_,
  ws_,
  sm_,
  st_,
  sa_,
  se_,
  ch_,
  sn_,
  rs_,
  sc_,
  sl_,
  zw_,
  sg_,
  sk_,
  si_,
  so_,
  es_,
  lk_,
  kn_,
  lc_,
  vc_,
  za_,
  sd_,
  ss_,
  sr_,
  sy_,
  tj_,
  tz_,
  th_,
  tl_,
  tg_,
  to_,
  tt_,
  td_,
  cz_,
  tn_,
  tr_,
  tm_,
  tv_,
  ug_,
  ua_,
  hu_,
  uy_,
  uz_,
  vu_,
  ve_,
  ae_,
  us_,
  gb_,
  vn_,
  cf_,
  cy_;

  String get string => toString().split(".").last.replaceAll("_", "");

  static Country fromString(String s) => Country.values.firstWhere((country) => country.string == s);

  Currency get currency => switch (this) {
        Country.au_ || Country.ki_ || Country.nr_ || Country.tv_ => Currency.aud_,
        Country.bs_ || Country.ec_ || Country.sv_ || Country.mh_ || Country.fm_ || Country.pw_ || Country.pa_ || Country.zw_ || Country.tl_ || Country.us_ => Currency.usd_,
        Country.bg_ => Currency.bgn_,
        Country.br_ => Currency.brl_,
        Country.ca_ => Currency.cad_,
        Country.li_ || Country.ch_ => Currency.chf_,
        Country.cn_ => Currency.cny_,
        Country.cz_ => Currency.czk_,
        Country.dk_ => Currency.dkk_,
        Country.gb_ => Currency.gbp_,
        Country.hu_ => Currency.huf_,
        Country.id_ => Currency.idr_,
        Country.il_ => Currency.ils_,
        Country.in_ => Currency.inr_,
        Country.is_ => Currency.isk_,
        Country.jp_ => Currency.jpy_,
        Country.kr_ => Currency.krw_,
        Country.mx_ => Currency.mxn_,
        Country.my_ => Currency.myr_,
        Country.no_ => Currency.nok_,
        Country.ck_ || Country.nz_ || Country.nu_ => Currency.nzd_,
        Country.ph_ => Currency.php_,
        Country.pl_ => Currency.pln_,
        Country.ro_ => Currency.ron_,
        Country.se_ => Currency.sek_,
        Country.sg_ => Currency.sgd_,
        Country.th_ => Currency.thb_,
        Country.tr_ => Currency.try_,
        Country.za_ => Currency.zar_,
        _ => Currency.eur_,
      };

  String get uiString => switch (this) {
        Country.af_ => 'Afghanistan',
        Country.eg_ => 'Egypt',
        Country.al_ => 'Albania',
        Country.dz_ => 'Algeria',
        Country.ad_ => 'Andorra',
        Country.ao_ => 'Angola',
        Country.ag_ => 'Antigua and Barbuda',
        Country.gq_ => 'Equatorial Guinea',
        Country.ar_ => 'Argentina',
        Country.am_ => 'Armenia',
        Country.az_ => 'Azerbaijan',
        Country.et_ => 'Ethiopia',
        Country.au_ => 'Australia',
        Country.bs_ => 'Bahamas',
        Country.bh_ => 'Bahrain',
        Country.bd_ => 'Bangladesh',
        Country.bb_ => 'Barbados',
        Country.by_ => 'Belarus',
        Country.be_ => 'Belgium',
        Country.bz_ => 'Belize',
        Country.bj_ => 'Benin',
        Country.bt_ => 'Bhutan',
        Country.bo_ => 'Bolivia',
        Country.ba_ => 'Bosnia and Herzegovina',
        Country.bw_ => 'Botswana',
        Country.br_ => 'Brazil',
        Country.bn_ => 'Brunei Darussalam',
        Country.bg_ => 'Bulgaria',
        Country.bf_ => 'Burkina Faso',
        Country.bi_ => 'Burundi',
        Country.cv_ => 'Cabo Verde',
        Country.cl_ => 'Chile',
        Country.cn_ => 'China',
        Country.ck_ => 'Cook Islands',
        Country.cr_ => 'Costa Rica',
        Country.ci_ => 'Cote d\'Ivoire',
        Country.dk_ => 'Denmark',
        Country.de_ => 'Germany',
        Country.dm_ => 'Dominica',
        Country.do_ => 'Dominican Republic',
        Country.dj_ => 'Djibouti',
        Country.ec_ => 'Ecuador',
        Country.sv_ => 'El Salvador',
        Country.er_ => 'Eritrea',
        Country.ee_ => 'Estonia',
        Country.sz_ => 'Eswatini',
        Country.fj_ => 'Fiji',
        Country.fi_ => 'Finland',
        Country.fr_ => 'France',
        Country.ga_ => 'Gabon',
        Country.gm_ => 'Gambia',
        Country.ge_ => 'Georgia',
        Country.gh_ => 'Ghana',
        Country.gd_ => 'Grenada',
        Country.gr_ => 'Greece',
        Country.gt_ => 'Guatemala',
        Country.gn_ => 'Guinea',
        Country.gw_ => 'Guinea-Bissau',
        Country.gy_ => 'Guyana',
        Country.ht_ => 'Haiti',
        Country.va_ => 'Holy See',
        Country.hn_ => 'Honduras',
        Country.in_ => 'India',
        Country.id_ => 'Indonesia',
        Country.iq_ => 'Iraq',
        Country.ir_ => 'Iran (Islamic Republic of)',
        Country.ie_ => 'Ireland',
        Country.is_ => 'Iceland',
        Country.il_ => 'Israel',
        Country.it_ => 'Italy',
        Country.jm_ => 'Jamaica',
        Country.jp_ => 'Japan',
        Country.ye_ => 'Yemen',
        Country.jo_ => 'Jordan',
        Country.kh_ => 'Cambodia',
        Country.cm_ => 'Cameroon',
        Country.ca_ => 'Canada',
        Country.kz_ => 'Kazakhstan',
        Country.qa_ => 'Qatar',
        Country.ke_ => 'Kenya',
        Country.kg_ => 'Kyrgyzstan',
        Country.ki_ => 'Kiribati',
        Country.co_ => 'Colombia',
        Country.km_ => 'Comoros',
        Country.cg_ => 'Congo',
        Country.cd_ => 'Congo (Democratic Republic of the)',
        Country.kp_ => 'Korea (Democratic People\'s Republic of)',
        Country.kr_ => 'Korea (Republic of)',
        Country.xk_ => 'Kosovo',
        Country.hr_ => 'Croatia',
        Country.cu_ => 'Cuba',
        Country.kw_ => 'Kuwait',
        Country.la_ => 'Lao People\'s Democratic Republic',
        Country.ls_ => 'Lesotho',
        Country.lv_ => 'Latvia',
        Country.lb_ => 'Lebanon',
        Country.lr_ => 'Liberia',
        Country.ly_ => 'Libya',
        Country.li_ => 'Liechtenstein',
        Country.lt_ => 'Lithuania',
        Country.lu_ => 'Luxembourg',
        Country.mg_ => 'Madagascar',
        Country.mw_ => 'Malawi',
        Country.my_ => 'Malaysia',
        Country.mv_ => 'Maldives',
        Country.ml_ => 'Mali',
        Country.mt_ => 'Malta',
        Country.ma_ => 'Morocco',
        Country.mh_ => 'Marshall Islands',
        Country.mr_ => 'Mauritania',
        Country.mu_ => 'Mauritius',
        Country.mx_ => 'Mexico',
        Country.fm_ => 'Micronesia (Federated States of)',
        Country.md_ => 'Moldova (Republic of)',
        Country.mc_ => 'Monaco',
        Country.mn_ => 'Mongolia',
        Country.me_ => 'Montenegro',
        Country.mz_ => 'Mozambique',
        Country.mm_ => 'Myanmar',
        Country.na_ => 'Namibia',
        Country.nr_ => 'Nauru',
        Country.np_ => 'Nepal',
        Country.nz_ => 'New Zealand',
        Country.ni_ => 'Nicaragua',
        Country.nl_ => 'Netherlands',
        Country.ne_ => 'Niger',
        Country.ng_ => 'Nigeria',
        Country.nu_ => 'Niue',
        Country.mk_ => 'North Macedonia',
        Country.no_ => 'Norway',
        Country.om_ => 'Oman',
        Country.at_ => 'Austria',
        Country.pk_ => 'Pakistan',
        Country.pw_ => 'Palau',
        Country.pa_ => 'Panama',
        Country.pg_ => 'Papua New Guinea',
        Country.py_ => 'Paraguay',
        Country.pe_ => 'Peru',
        Country.ph_ => 'Philippines',
        Country.pl_ => 'Poland',
        Country.pt_ => 'Portugal',
        Country.rw_ => 'Rwanda',
        Country.ro_ => 'Romania',
        Country.ru_ => 'Russian Federation',
        Country.sb_ => 'Solomon Islands',
        Country.zm_ => 'Zambia',
        Country.ws_ => 'Samoa',
        Country.sm_ => 'San Marino',
        Country.st_ => 'Sao Tome and Principe',
        Country.sa_ => 'Saudi Arabia',
        Country.se_ => 'Sweden',
        Country.ch_ => 'Switzerland',
        Country.sn_ => 'Senegal',
        Country.rs_ => 'Serbia',
        Country.sc_ => 'Seychelles',
        Country.sl_ => 'Sierra Leone',
        Country.zw_ => 'Zimbabwe',
        Country.sg_ => 'Singapore',
        Country.sk_ => 'Slovakia',
        Country.si_ => 'Slovenia',
        Country.so_ => 'Somalia',
        Country.es_ => 'Spain',
        Country.lk_ => 'Sri Lanka',
        Country.kn_ => 'Saint Kitts and Nevis',
        Country.lc_ => 'Saint Lucia',
        Country.vc_ => 'Saint Vincent and the Grenadines',
        Country.za_ => 'South Africa',
        Country.sd_ => 'Sudan',
        Country.ss_ => 'South Sudan',
        Country.sr_ => 'Suriname',
        Country.sy_ => 'Syrian Arab Republic',
        Country.tj_ => 'Tajikistan',
        Country.tz_ => 'Tanzania, United Republic of',
        Country.th_ => 'Thailand',
        Country.tl_ => 'Timor-Leste',
        Country.tg_ => 'Togo',
        Country.to_ => 'Tonga',
        Country.tt_ => 'Trinidad and Tobago',
        Country.td_ => 'Chad',
        Country.cz_ => 'Czechia',
        Country.tn_ => 'Tunisia',
        Country.tr_ => 'Turkey',
        Country.tm_ => 'Turkmenistan',
        Country.tv_ => 'Tuvalu',
        Country.ug_ => 'Uganda',
        Country.ua_ => 'Ukraine',
        Country.hu_ => 'Hungary',
        Country.uy_ => 'Uruguay',
        Country.uz_ => 'Uzbekistan',
        Country.vu_ => 'Vanuatu',
        Country.ve_ => 'Venezuela (Bolivarian Republic of)',
        Country.ae_ => 'United Arab Emirates',
        Country.us_ => 'United States of America',
        Country.gb_ => 'United Kingdom of Great Britain and Northern Ireland',
        Country.vn_ => 'Viet Nam',
        Country.cf_ => 'Central African Republic',
        Country.cy_ => 'Cyprus',
      };
}
