enum Currency {
  eur_,
  usd_,
  jpy_,
  bgn_,
  czk_,
  dkk_,
  gbp_,
  huf_,
  pln_,
  ron_,
  sek_,
  chf_,
  isk_,
  nok_,
  try_,
  aud_,
  brl_,
  cad_,
  cny_,
  hkd_,
  idr_,
  ils_,
  inr_,
  krw_,
  mxn_,
  myr_,
  nzd_,
  php_,
  sgd_,
  thb_,
  zar_;

  String get string => toString().split(".").last.replaceAll("_", "");

  static Currency fromString(String s) => Currency.values.firstWhere((v) => v.string == s);

  String get uiString => switch (this) {
        Currency.eur_ => "€",
        Currency.usd_ => "\$",
        Currency.jpy_ => "¥",
        Currency.bgn_ => "лв",
        Currency.czk_ => "Kč",
        Currency.dkk_ => "kr",
        Currency.gbp_ => "£",
        Currency.huf_ => "Ft",
        Currency.pln_ => "zł",
        Currency.ron_ => "lei",
        Currency.sek_ => "kr",
        Currency.chf_ => "CHF",
        Currency.isk_ => "kr",
        Currency.nok_ => "kr",
        Currency.try_ => "₺",
        Currency.aud_ => "\$",
        Currency.brl_ => "R\$",
        Currency.cad_ => "\$",
        Currency.cny_ => "¥",
        Currency.hkd_ => "\$",
        Currency.idr_ => "Rp",
        Currency.ils_ => "₪",
        Currency.inr_ => "₹",
        Currency.krw_ => "₩",
        Currency.mxn_ => "\$",
        Currency.myr_ => "RM",
        Currency.nzd_ => "\$",
        Currency.php_ => "₱",
        Currency.sgd_ => "\$",
        Currency.thb_ => "฿",
        Currency.zar_ => "R",
      };
}
