import 'package:easywear_models/easywear_models.dart';

enum EasyWearFile {
  byod,
  excelTool,
  excelTutorial,
  exchangeProtocol,
  orderForm;

  FileType get fileType => switch (this) {
        EasyWearFile.byod => FileType.pdf,
        EasyWearFile.excelTool => FileType.xlsx,
        EasyWearFile.excelTutorial => FileType.pdf,
        EasyWearFile.exchangeProtocol => FileType.pdf,
        EasyWearFile.orderForm => FileType.pdf,
      };

  String systematicFilename(Language language) => "${string}_${language.string}.${fileType.string}";

  String prettyFilename(Language language) => switch (this) {
        EasyWearFile.byod => switch (language) {
            Language.de => "Bring your own Device.pdf",
            Language.en => "Bring your own Device.pdf",
            Language.fr => "Apportez votre propre appareil.pdf",
            Language.it => "Porta il tuo dispositivo.pdf",
            Language.es => "Trae tu propio dispositivo.pdf",
            Language.nl => "Neem je eigen apparaat mee.pdf",
            Language.ru => "Принеси свое устройство.pdf",
            Language.tr => "Kendi Cihazını Getir.pdf",
            Language.no => "Ta med egen enhet.pdf",
            Language.da => "Medbring din egen enhed.pdf",
            Language.sv => "Ta med egen enhet.pdf",
            Language.ar => "أحضر جهازك الخاص.pdf",
            Language.zh => "自带设备.pdf",
            Language.th => "นำอุปกรณ์มาเอง.pdf",
            Language.vi => "Mang thiết bị của riêng bạn.pdf",
            Language.cs => "Přineste si vlastní zařízení.pdf",
            Language.el => "Φέρτε τη δική σας συσκευή.pdf",
            Language.uk => "Принесіть свій власний пристрій.pdf",
            Language.hr => "Donesite vlastiti uređaj.pdf",
            Language.ja => "自分のデバイスを持参.pdf",
            Language.pl => "Przynieś własne urządzenie.pdf",
            Language.pt => "Traga seu próprio dispositivo.pdf",
            Language.ko => "개인 기기 지참.pdf",
            Language.ur => "اپنا آلہ ساتھ لائیں۔pdf",
            Language.bg => "Донесете си собствено устройство.pdf",
            Language.af => "Bring jou eie toestel.pdf",
            Language.hi => "अपना उपकरण लाएं.pdf",
          },
        EasyWearFile.excelTool => switch (language) {
            Language.de => "Arbeitskleidung Verwaltung EasyWear.xlsx",
            Language.en => "Workwear Management EasyWear.xlsx",
            Language.fr => "Gestion des vêtements de travail EasyWear.xlsx",
            Language.it => "Gestione abbigliamento da lavoro EasyWear.xlsx",
            Language.es => "Gestión de ropa de trabajo EasyWear.xlsx",
            Language.nl => "Bedrijfskleding Beheer EasyWear.xlsx",
            Language.ru => "Управление спецодеждой EasyWear.xlsx",
            Language.tr => "İş Elbisesi Yönetimi EasyWear.xlsx",
            Language.no => "Arbeidsklærstyring EasyWear.xlsx",
            Language.da => "Arbejdstøj Styring EasyWear.xlsx",
            Language.sv => "Arbetskläder Hantering EasyWear.xlsx",
            Language.ar => "إدارة ملابس العمل EasyWear.xlsx",
            Language.zh => "工作服管理EasyWear.xlsx",
            Language.th => "การจัดการชุดทำงาน EasyWear.xlsx",
            Language.vi => "Quản lý đồng phục EasyWear.xlsx",
            Language.cs => "Správa pracovních oděvů EasyWear.xlsx",
            Language.el => "Διαχείριση Ενδυμάτων Εργασίας EasyWear.xlsx",
            Language.uk => "Управління робочим одягом EasyWear.xlsx",
            Language.hr => "Upravljanje radnom odjećom EasyWear.xlsx",
            Language.ja => "作業服管理EasyWear.xlsx",
            Language.pl => "Zarządzanie odzieżą roboczą EasyWear.xlsx",
            Language.pt => "Gestão de Vestuário de Trabalho EasyWear.xlsx",
            Language.ko => "작업복 관리 EasyWear.xlsx",
            Language.ur => "ورک ویئر مینجمنٹ ایزی وئیر.xlsx",
            Language.bg => "Управление на работно облекло EasyWear.xlsx",
            Language.af => "Werksklerebestuur EasyWear.xlsx",
            Language.hi => "वर्कवियर प्रबंधन EasyWear.xlsx",
          },
        EasyWearFile.excelTutorial => switch (language) {
            Language.de => "Excel Tutorial.pdf",
            Language.en => "Excel Tutorial.pdf",
            Language.fr => "Tutoriel Excel.pdf",
            Language.it => "Tutorial Excel.pdf",
            Language.es => "Tutorial de Excel.pdf",
            Language.nl => "Excel handleiding.pdf",
            Language.ru => "Учебник Excel.pdf",
            Language.tr => "Excel Eğitimi.pdf",
            Language.no => "Excel-opplæring.pdf",
            Language.da => "Excel-vejledning.pdf",
            Language.sv => "Excel-handledning.pdf",
            Language.ar => "برنامج تعليمي لإكسل.pdf",
            Language.zh => "Excel 教程.pdf",
            Language.th => "บทเรียน Excel.pdf",
            Language.vi => "Hướng dẫn Excel.pdf",
            Language.cs => "Výukový program Excel.pdf",
            Language.el => "Εκπαιδευτικό Excel.pdf",
            Language.uk => "Навчальний посібник з Excel.pdf",
            Language.hr => "Excel Vodič.pdf",
            Language.ja => "Excelチュートリアル.pdf",
            Language.pl => "Samouczek Excel.pdf",
            Language.pt => "Tutorial Excel.pdf",
            Language.ko => "엑셀 튜토리얼.pdf",
            Language.ur => "ایکسل ٹیوٹوریل.pdf",
            Language.bg => "Урок по Excel.pdf",
            Language.af => "Excel Tutoriaal.pdf",
            Language.hi => "एक्सेल ट्यूटोरियल.pdf",
          },
        EasyWearFile.exchangeProtocol => switch (language) {
            Language.de => "Uebergaberotokoll fuer Arbeitskleidung.pdf",
            Language.en => "Workwear Handover Protocol.pdf",
            Language.fr => "Protocole de remise des vêtements de travail.pdf",
            Language.it => "Protocollo di consegna dell'abbigliamento da lavoro.pdf",
            Language.es => "Protocolo de entrega de ropa de trabajo.pdf",
            Language.nl => "Overdrachtsprotocol bedrijfskleding.pdf",
            Language.ru => "Протокол передачи спецодежды.pdf",
            Language.tr => "İş Elbisesi Teslim Protokolü.pdf",
            Language.no => "Protokoll for overlevering av arbeidsklær.pdf",
            Language.da => "Overdragelsesprotokol for arbejdstøj.pdf",
            Language.sv => "Överlämningsprotokoll för arbetskläder.pdf",
            Language.ar => "بروتوكول تسليم ملابس العمل.pdf",
            Language.zh => "工作服交接协议.pdf",
            Language.th => "พิธีสารการส่งมอบชุดทำงาน.pdf",
            Language.vi => "Nghị định thư bàn giao đồng phục.pdf",
            Language.cs => "Předávací protokol pracovních oděvů.pdf",
            Language.el => "Πρωτόκολλο Παράδοσης Ενδυμάτων Εργασίας.pdf",
            Language.uk => "Протокол передачі робочого одягу.pdf",
            Language.hr => "Protokol primopredaje radne odjeće.pdf",
            Language.ja => "作業服引渡プロトコル.pdf",
            Language.pl => "Protokół przekazania odzieży roboczej.pdf",
            Language.pt => "Protocolo de Entrega de Vestuário de Trabalho.pdf",
            Language.ko => "작업복 인계 프로토콜.pdf",
            Language.ur => "ورک ویئر ہینڈ اوور پروٹوکول.pdf",
            Language.bg => "Протокол за предаване на работно облекло.pdf",
            Language.af => "Oordragsprotokol vir werksklere.pdf",
            Language.hi => "वर्कवियर हैंडओवर प्रोटोकॉल.pdf",
          },
        EasyWearFile.orderForm => switch (language) {
            Language.de => "Bestellformular.pdf",
            Language.en => "Order Form.pdf",
            Language.fr => "Formulaire de commande.pdf",
            Language.it => "Modulo d'ordine.pdf",
            Language.es => "Formulario de pedido.pdf",
            Language.nl => "Bestelformulier.pdf",
            Language.ru => "Форма заказа.pdf",
            Language.tr => "Sipariş Formu.pdf",
            Language.no => "Bestillingsskjema.pdf",
            Language.da => "Bestillingsformular.pdf",
            Language.sv => "Beställningsformulär.pdf",
            Language.ar => "نموذج الطلب.pdf",
            Language.zh => "订单表格.pdf",
            Language.th => "แบบฟอร์มสั่งซื้อ.pdf",
            Language.vi => "Mẫu đơn đặt hàng.pdf",
            Language.cs => "Objednávkový formulář.pdf",
            Language.el => "Έντυπο Παραγγελίας.pdf",
            Language.uk => "Форма замовлення.pdf",
            Language.hr => "Obrazac za narudžbu.pdf",
            Language.ja => "注文書.pdf",
            Language.pl => "Formularz zamówienia.pdf",
            Language.pt => "Formulário de Pedido.pdf",
            Language.ko => "주문 양식.pdf",
            Language.ur => "آرڈر فارم.pdf",
            Language.bg => "Формуляр за поръчка.pdf",
            Language.af => "Bestelformulier.pdf",
            Language.hi => "ऑर्डर फ़ॉर्म.pdf",
          },
      };
}

enum FileType {
  pdf,
  csv,
  xlsx;
}
