import 'package:easywear_models/easywear_models.dart';

enum FeatureLevel {
  free,
  basic,
  premium,
  enterprise;

  static FeatureLevel fromString(String s) =>
      FeatureLevel.values.firstWhere((e) => e.string == s);

  String uiText(Language language) => switch (this) {
        FeatureLevel.free => switch (language) {
            Language.de => "Kostenlos",
            Language.en => "Free",
            Language.fr => "Gratuit",
            Language.it => "Gratuito",
            Language.es => "Gratis",
            Language.nl => "Gratis",
            Language.ru => "Бесплатно",
            Language.tr => "Ücretsiz",
            Language.no => "Gratis",
            Language.da => "Gratis",
            Language.sv => "Gratis",
            Language.ar => "مجاني",
            Language.zh => "免费",
            Language.th => "ฟรี",
            Language.vi => "Miễn phí",
            Language.cs => "Zdarma",
            Language.el => "Δωρεάν",
            Language.uk => "Безкоштовно",
            Language.hr => "Besplatno",
            Language.ja => "無料",
            Language.pl => "Darmowy",
            Language.pt => "Gratuito",
            Language.ko => "무료",
            Language.ur => "مفت",
            Language.bg => "Безплатно",
            Language.af => "Gratis",
            Language.hi => "मुफ़्त",
          },
        FeatureLevel.basic => switch (language) {
            Language.de => "Basis",
            Language.en => "Basic",
            Language.fr => "Basique",
            Language.it => "Base",
            Language.es => "Básico",
            Language.nl => "Basis",
            Language.ru => "Базовый",
            Language.tr => "Temel",
            Language.no => "Grunnleggende",
            Language.da => "Grundlæggende",
            Language.sv => "Grundläggande",
            Language.ar => "أساسي",
            Language.zh => "基础版",
            Language.th => "พื้นฐาน",
            Language.vi => "Cơ bản",
            Language.cs => "Základní",
            Language.el => "Βασικό",
            Language.uk => "Базовий",
            Language.hr => "Osnovni",
            Language.ja => "基本的な",
            Language.pl => "Podstawowy",
            Language.pt => "Básico",
            Language.ko => "기본",
            Language.ur => "بنیادی",
            Language.bg => "Основен",
            Language.af => "Basies",
            Language.hi => "बुनियादी",
          },
        FeatureLevel.premium => switch (language) {
            Language.de => "Premium",
            Language.en => "Premium",
            Language.fr => "Premium",
            Language.it => "Premium",
            Language.es => "Premium",
            Language.nl => "Premium",
            Language.ru => "Премиум",
            Language.tr => "Premium",
            Language.no => "Premium",
            Language.da => "Premium",
            Language.sv => "Premium",
            Language.ar => "مميز",
            Language.zh => "高级版",
            Language.th => "พรีเมียม",
            Language.vi => "Cao cấp",
            Language.cs => "Prémiový",
            Language.el => "Πριμοδότηση",
            Language.uk => "Преміум",
            Language.hr => "Premium",
            Language.ja => "プレミアム",
            Language.pl => "Premium",
            Language.pt => "Premium",
            Language.ko => "프리미엄",
            Language.ur => "پریمیم",
            Language.bg => "Премиум",
            Language.af => "Premieum",
            Language.hi => "प्रीमियम",
          },
        FeatureLevel.enterprise => switch (language) {
            Language.de => "Enterprise",
            Language.en => "Enterprise",
            Language.fr => "Entreprise",
            Language.it => "Impresa",
            Language.es => "Empresa",
            Language.nl => "Enterprise",
            Language.ru => "Корпоративный",
            Language.tr => "Kurumsal",
            Language.no => "Bedrift",
            Language.da => "Virksomhed",
            Language.sv => "Företag",
            Language.ar => "مؤسسة",
            Language.zh => "企业版",
            Language.th => "องค์กร",
            Language.vi => "Doanh nghiệp",
            Language.cs => "Podnikový",
            Language.el => "Επιχειρηματικό",
            Language.uk => "Корпоративний",
            Language.hr => "Poduzeće",
            Language.ja => "エンタープライズ",
            Language.pl => "Enterprise",
            Language.pt => "Empresa",
            Language.ko => "기업용",
            Language.ur => "انٹرپرائز",
            Language.bg => "Корпоративен",
            Language.af => "Onderneming",
            Language.hi => "एंटरप्राइज",
          },
      };
}
