import 'package:easywear_models/easywear_models.dart';

enum RequestType {
  order,
  claim,
  correction;

  static RequestType fromString(String s) => RequestType.values.firstWhere((v) => v.string == s);

  String uiText(Language language) => switch (this) {
        RequestType.order => switch (language) {
            Language.de => "Bestellung",
            Language.en => "Order",
            Language.fr => "Commande",
            Language.it => "Ordine",
            Language.es => "Pedido",
            Language.nl => "Bestelling",
            Language.ru => "Заказ",
            Language.tr => "Sipariş",
            Language.no => "Bestilling",
            Language.da => "Bestilling",
            Language.sv => "Beställning",
            Language.ar => "طلب",
            Language.zh => "订单",
            Language.th => "คำสั่งซื้อ",
            Language.vi => "Đơn hàng",
            Language.cs => "Objednávka",
            Language.el => "Παραγγελία",
            Language.uk => "Замовлення",
            Language.hr => "Narudžba",
            Language.ja => "注文",
            Language.pl => "Zamówienie",
            Language.pt => "Pedido",
            Language.ko => "주문",
            Language.ur => "آرڈر",
            Language.bg => "Поръчка",
            Language.af => "Bestelling",
            Language.hi => "ऑर्डर",
          },
        RequestType.claim => switch (language) {
            Language.de => "Reklamation",
            Language.en => "Complaint",
            Language.fr => "Réclamation",
            Language.it => "Reclamo",
            Language.es => "Reclamación",
            Language.nl => "Klacht",
            Language.ru => "Жалоба",
            Language.tr => "Şikayet",
            Language.no => "Klage",
            Language.da => "Klage",
            Language.sv => "Klagomål",
            Language.ar => "شكوى",
            Language.zh => "投诉",
            Language.th => "คำร้องเรียน",
            Language.vi => "Khiếu nại",
            Language.cs => "Reklamace",
            Language.el => "Καταγγελία",
            Language.uk => "Скарга",
            Language.hr => "Žalba",
            Language.ja => "苦情",
            Language.pl => "Reklamacja",
            Language.pt => "Reclamação",
            Language.ko => "불만",
            Language.ur => "شکایت",
            Language.bg => "Жалба",
            Language.af => "Klagte",
            Language.hi => "शिकायत",
          },
        RequestType.correction => switch (language) {
            Language.de => "Inventarkorrektur",
            Language.en => "Inventory correction",
            Language.fr => "Correction d'inventaire",
            Language.it => "Correzione inventario",
            Language.es => "Corrección de inventario",
            Language.nl => "Voorraadcorrectie",
            Language.ru => "Коррекция инвентаря",
            Language.tr => "Stok düzeltmesi",
            Language.no => "Lagerkorreksjon",
            Language.da => "Lagerkorrektion",
            Language.sv => "Inventarie korrigering",
            Language.ar => "تصحيح الجرد",
            Language.zh => "库存更正",
            Language.th => "การแก้ไขสินค้าคงคลัง",
            Language.vi => "Sửa chữa tồn kho",
            Language.cs => "Korekce inventáře",
            Language.el => "Διόρθωση αποθέματος",
            Language.uk => "Корекція інвентаризації",
            Language.hr => "Ispravak inventara",
            Language.ja => "在庫修正",
            Language.pl => "Korekta inwentarza",
            Language.pt => "Correção de inventário",
            Language.ko => "재고 수정",
            Language.ur => "انفینٹری کی تصحیح",
            Language.bg => "Корекция на инвентара",
            Language.af => "Inventaris regstelling",
            Language.hi => "संपत्ति सुधार",
          },
      };
}
